import { CONTROLLER_NAME } from './controller-name.constant';

export const COURCE_SERVICE_URL = {
    ACTION_ADD_COURSE_HIERARCHY: CONTROLLER_NAME.COURSE_CONTROLLER + "/AddCourseHierarchy",
    ACTION_UPDATE_COURSE_HIERARCHY: CONTROLLER_NAME.COURSE_CONTROLLER + "/UpdateCourseHierarchy",
    ACTION_GET_COURSE_HIERARCHY: CONTROLLER_NAME.COURSE_CONTROLLER + "/GetCourseHierarchy",
    ACTION_MAKE_INACTIVE_COURSE_HIERARCHY: CONTROLLER_NAME.COURSE_CONTROLLER + "/MakeInActiveCourseHierarchy",
}

 