export * from "./settings-index.component"
export * from "./subject/subject.component"
export * from "./org-settings/org.component"
export * from "./course/course.component"
export * from "./standards/standards.component"