

/*!50003 DROP TRIGGER*//*!50032 IF EXISTS */ /*!50003 `TRG_USER_AUDIT_UPDATE` */$$

/*!50003 CREATE */ /*!50017 DEFINER = 'trishakti'@'%' */ /*!50003 TRIGGER `TRG_USER_AUDIT_UPDATE` BEFORE UPDATE ON `USER_MASTER` FOR EACH ROW BEGIN
    
     DECLARE P_OPERATION INTEGER;
      
      
       
    INSERT INTO USER_MASTER_AUDIT(
    
	USER_ID,
	LOGIN_ID,
	PASSWORD ,
	FIRST_NAME ,
	MIDDLE_NAME ,
	LAST_NAME,
	USER_TYPE_ID ,
	CUSTOMER_ID ,
	CONTACT_NO  ,
	ADDRESS  ,
	NOTIFICATION_ID ,
	CREATED_DATE  ,
	CREATED_BY ,
	MODIFIED_DATE ,
	MODIFIED_BY  ,
	OPERARTION_DATE,
	OPERATION
    )
    VALUES(
OLD.ID,
	OLD.LOGIN_ID,
	OLD.PASSWORD ,
	OLD.FIRST_NAME ,
	OLD.MIDDLE_NAME ,
	OLD.LAST_NAME,
	OLD.USER_TYPE_ID ,
	OLD.CUSTOMER_ID ,
	OLD.CONTACT_NO  ,
	OLD.ADDRESS  ,
	OLD.NOTIFICATION_ID ,
	OLD.CREATED_DATE  ,
	OLD.CREATED_BY ,
	OLD.MODIFIED_DATE ,
	NEW.MODIFIED_BY ,
	NOW(),
	1
	     
    );
    END */$$

