/*
SQLyog Community
MySQL - 8.0.18 : Database - ved_soft_db
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
/*Table structure for table `ACADEMIC_YEARS` */

CREATE TABLE `ACADEMIC_YEARS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ACADEMIC_YEAR` varchar(50) DEFAULT NULL,
  `ACTIVE` int(1) DEFAULT NULL,
  `CREATED_BY` int(11) DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT NULL,
  `MODIFIED_BY` int(11) DEFAULT NULL,
  `MODIFIED_DATE` datetime DEFAULT NULL,
  `CUSTOMER_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `ADMISSION_TYPE` */

CREATE TABLE `ADMISSION_TYPE` (
  `ID` int(11) NOT NULL,
  `NAME` varchar(100) DEFAULT NULL,
  `ACTIVE` int(1) DEFAULT NULL,
  `CREATED_BY` int(11) DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT NULL,
  `MODIFIED_BY` int(11) DEFAULT NULL,
  `MODIFIED_DATE` datetime DEFAULT NULL,
  `CUSTOMER_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `BANK` */

CREATE TABLE `BANK` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(150) DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT NULL,
  `CUSTOMER_ID` int(11) DEFAULT NULL,
  `ACTIVE` int(1) DEFAULT NULL,
  `CREATED_BY` int(11) DEFAULT NULL,
  `MODIFIED_BY` int(11) DEFAULT NULL,
  `MODIFIED_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `BRANCH_COURSES` */

CREATE TABLE `BRANCH_COURSES` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CUSTOMER_COURSES_ID` varchar(250) DEFAULT NULL,
  `BRANCH_ID` int(11) DEFAULT NULL,
  `ACADEMIC_YEAR_ID` int(11) DEFAULT NULL,
  `ACTIVE` int(11) DEFAULT NULL,
  `COURSE_DURATION_MONTHS` varchar(250) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `BRANCH_COURSES_FK2` (`BRANCH_ID`),
  CONSTRAINT `BRANCH_COURSES_FK2` FOREIGN KEY (`BRANCH_ID`) REFERENCES `CUSTOMER_BRANCHES` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `CUSTOMER_BRANCHES` */

CREATE TABLE `CUSTOMER_BRANCHES` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CUSTOMER_ID` int(11) DEFAULT NULL,
  `CODE` varchar(150) NOT NULL,
  `NAME` varchar(250) NOT NULL,
  `ACTIVE` int(11) NOT NULL,
  `CONTACT_NO` json DEFAULT NULL,
  `ADDRESS` json DEFAULT NULL,
  `OTHER_INFO` json DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT NULL,
  `CREATED_BY` int(11) DEFAULT NULL,
  `MODIFIED_DATE` datetime DEFAULT NULL,
  `MODIFIED_BY` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `CODE` (`CODE`),
  UNIQUE KEY `NAME` (`NAME`),
  KEY `BRANCH_MASTER_FK` (`CUSTOMER_ID`),
  CONSTRAINT `BRANCH_MASTER_FK` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `CUSTOMER_MASTER` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `CUSTOMER_COURSES` */

CREATE TABLE `CUSTOMER_COURSES` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(250) DEFAULT NULL,
  `CUSTOMER_ID` int(11) DEFAULT NULL,
  `ACTIVE` int(1) unsigned DEFAULT '1',
  `VEDIC_COURSE_ID` int(11) DEFAULT NULL,
  `COURSE_TYPE_ID` int(11) DEFAULT NULL,
  `COURSE_DESCRIPTION` varchar(250) DEFAULT NULL,
  `DURATION` int(11) DEFAULT NULL,
  `DURATION_UOM` varchar(50) DEFAULT NULL,
  `COURSE_COST` decimal(10,0) DEFAULT NULL,
  `CREATED_BY` int(11) DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT NULL,
  `MODIFIED_BY` int(11) DEFAULT NULL,
  `MODIFIED_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `CUSTOMER_COURSES_FK1` (`VEDIC_COURSE_ID`),
  KEY `CUSTOMER_COURSES_FK2` (`CUSTOMER_ID`),
  CONSTRAINT `CUSTOMER_COURSES_FK1` FOREIGN KEY (`VEDIC_COURSE_ID`) REFERENCES `VEDIC_COURSES_MASTER` (`ID`),
  CONSTRAINT `CUSTOMER_COURSES_FK2` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `CUSTOMER_MASTER` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `CUSTOMER_COURSE_SUBJECT_MAPPING` */

CREATE TABLE `CUSTOMER_COURSE_SUBJECT_MAPPING` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CUSTOMER_ID` int(11) NOT NULL,
  `CUSTOMER_COURSE_ID` int(11) NOT NULL,
  `CUSTOMER_SUBJECT_HIERACHY_ID` int(11) NOT NULL,
  `ACTIVE` int(1) DEFAULT '1',
  `CREATED_BY` int(11) DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT NULL,
  `MODIFIED_BY` int(11) DEFAULT NULL,
  `MODIFIED_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `CUSTOMER_COURSE_HIERACHY_MAPPING_FK1` (`CUSTOMER_SUBJECT_HIERACHY_ID`),
  KEY `CUSTOMER_COURSE_HIERACHY_MAPPING_FK2` (`CUSTOMER_COURSE_ID`),
  KEY `CUSTOMER_COURSE_HIERACHY_MAPPING_FK3` (`CUSTOMER_ID`),
  CONSTRAINT `CUSTOMER_COURSE_HIERACHY_MAPPING_FK1` FOREIGN KEY (`CUSTOMER_SUBJECT_HIERACHY_ID`) REFERENCES `CUSTOMER_SUBJECT_HIRARCHY` (`ID`),
  CONSTRAINT `CUSTOMER_COURSE_HIERACHY_MAPPING_FK2` FOREIGN KEY (`CUSTOMER_COURSE_ID`) REFERENCES `CUSTOMER_COURSES` (`ID`),
  CONSTRAINT `CUSTOMER_COURSE_HIERACHY_MAPPING_FK3` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `CUSTOMER_MASTER` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `CUSTOMER_EDUCATIONAL_INSTITUTIONS` */

CREATE TABLE `CUSTOMER_EDUCATIONAL_INSTITUTIONS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `INSTITUTION_TYPE_ID` int(11) DEFAULT NULL,
  `CUSTOMER_ID` int(11) DEFAULT NULL,
  `NAME` varchar(250) DEFAULT NULL,
  `ACTIVE` int(11) DEFAULT NULL,
  `CREATED_BY` int(11) DEFAULT NULL,
  `CREATED_DATE` date DEFAULT NULL,
  `MODIFIED_BY` int(11) DEFAULT NULL,
  `MODIFIED_DATE` date DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `CUSTOMER_EDUC_INSTITUTION_FK1` (`INSTITUTION_TYPE_ID`),
  KEY `CUSTOMER_EDUC_INSTITUTION_FK2` (`CUSTOMER_ID`),
  CONSTRAINT `CUSTOMER_EDUC_INSTITUTION_FK1` FOREIGN KEY (`INSTITUTION_TYPE_ID`) REFERENCES `VEDIC_INSTITUTION_TYPE` (`ID`),
  CONSTRAINT `CUSTOMER_EDUC_INSTITUTION_FK2` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `CUSTOMER_MASTER` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `CUSTOMER_MASTER` */

CREATE TABLE `CUSTOMER_MASTER` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CODE` varchar(150) NOT NULL,
  `NAME` varchar(250) NOT NULL,
  `SUB_DOMAIN` varchar(100) NOT NULL,
  `DESCRIPTION` varchar(150) DEFAULT NULL,
  `ACTIVE` int(11) NOT NULL,
  `CONTACT_NO` json DEFAULT NULL,
  `ADDRESS` json DEFAULT NULL,
  `OTHER_INFO` json DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT NULL,
  `CREATED_BY` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `CODE` (`CODE`),
  UNIQUE KEY `NAME` (`NAME`),
  UNIQUE KEY `SUB_DOMAIN` (`SUB_DOMAIN`)
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `CUSTOMER_ROLES` */

CREATE TABLE `CUSTOMER_ROLES` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(250) DEFAULT NULL,
  `DESCRIPTION` varchar(250) DEFAULT NULL,
  `CUSTOMER_ID` int(11) NOT NULL,
  `ACTIVE` int(1) DEFAULT NULL,
  `CREATED_BY` int(11) DEFAULT NULL,
  `CREATED_DATE` date DEFAULT NULL,
  `MODIFIED_BY` int(11) DEFAULT NULL,
  `MODIFIED_DATE` date DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `CUSTOMER_ROLES_FK1` (`CUSTOMER_ID`),
  CONSTRAINT `CUSTOMER_ROLES_FK1` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `CUSTOMER_MASTER` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `CUSTOMER_ROLE_MODULE_PRIVILEGES` */

CREATE TABLE `CUSTOMER_ROLE_MODULE_PRIVILEGES` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CUSTOMER_ROLE_ID` int(11) DEFAULT NULL,
  `MODULE_PRIVILEGE_ID` int(11) DEFAULT NULL,
  `ACTIVE` int(1) DEFAULT NULL,
  `CREATED_BY` int(11) DEFAULT NULL,
  `CREATED_DATE` date DEFAULT NULL,
  `MODIFIED_BY` int(11) DEFAULT NULL,
  `MODIFIED_DATE` date DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `CUSTOMER_ROLE_MODULE_PRIVILEGES_FK1` (`CUSTOMER_ROLE_ID`),
  KEY `CUSTOMER_ROLE_MODULE_PRIVILEGES_FK2` (`MODULE_PRIVILEGE_ID`),
  CONSTRAINT `CUSTOMER_ROLE_MODULE_PRIVILEGES_ibfk_1` FOREIGN KEY (`CUSTOMER_ROLE_ID`) REFERENCES `CUSTOMER_ROLES` (`ID`),
  CONSTRAINT `CUSTOMER_ROLE_MODULE_PRIVILEGES_ibfk_2` FOREIGN KEY (`MODULE_PRIVILEGE_ID`) REFERENCES `MODULE_PRIVILEGES` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `CUSTOMER_ROLE_PRIVILEGES` */

CREATE TABLE `CUSTOMER_ROLE_PRIVILEGES` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CUSTOMER_ID` int(11) DEFAULT NULL,
  `CUSTOMER_ROLE_ID` int(11) DEFAULT NULL,
  `PRIVILEGE_TYPE_ID` int(11) DEFAULT NULL,
  `ACTIVE` int(1) DEFAULT NULL,
  `CREATED_BY` int(11) DEFAULT NULL,
  `CREATED_DATE` date DEFAULT NULL,
  `MODIFIED_BY` int(11) DEFAULT NULL,
  `MODIFIED_DATE` date DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `CUSTOMER_ROLES_FK1` (`CUSTOMER_ROLE_ID`),
  CONSTRAINT `CUSTOMER_ROLE_PRIVILEGES_ibfk_1` FOREIGN KEY (`CUSTOMER_ROLE_ID`) REFERENCES `CUSTOMER_ROLES` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `CUSTOMER_SUBJECT_HIRARCHY` */

CREATE TABLE `CUSTOMER_SUBJECT_HIRARCHY` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(250) DEFAULT NULL,
  `CUSTOMER_ID` int(11) DEFAULT NULL,
  `PARENT_ID` int(11) DEFAULT NULL,
  `HIERACHY_LEVEL` int(11) DEFAULT NULL,
  `ACTIVE` int(1) DEFAULT '1',
  `CREATED_BY` int(11) DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT NULL,
  `MODIFIED_BY` int(11) DEFAULT NULL,
  `MODIFIED_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `COURSES_STRUCTURE_HIERACHY_FK` (`PARENT_ID`),
  KEY `CUSTOMER_COURSE_HIERACHY_FK2` (`CUSTOMER_ID`),
  CONSTRAINT `COURSES_STRUCTURE_HIERACHY_FK` FOREIGN KEY (`PARENT_ID`) REFERENCES `CUSTOMER_SUBJECT_HIRARCHY` (`ID`),
  CONSTRAINT `CUSTOMER_COURSE_HIERACHY_FK2` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `CUSTOMER_MASTER` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=30 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `DEPARTMENT` */

CREATE TABLE `DEPARTMENT` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `BRANCH_ID` int(11) DEFAULT NULL,
  `NAME` varchar(250) DEFAULT NULL,
  `DESCRIPTION` varchar(250) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `DEPARTMENT_FK` (`BRANCH_ID`),
  CONSTRAINT `DEPARTMENT_FK` FOREIGN KEY (`BRANCH_ID`) REFERENCES `CUSTOMER_BRANCHES` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `JAI_MAA_BHAWANI` */

CREATE TABLE `JAI_MAA_BHAWANI` (
  `DESCRIPTION` varchar(2000) DEFAULT NULL,
  `CREATEDDATE` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `LANGUAGE_MASTER` */

CREATE TABLE `LANGUAGE_MASTER` (
  `ID` int(4) NOT NULL,
  `NAME` varchar(50) DEFAULT NULL,
  `CULTURE_CODE` varchar(5) DEFAULT NULL,
  `ACTIVE` tinyint(1) DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `MODULE_MASTER` */

CREATE TABLE `MODULE_MASTER` (
  `ID` int(4) NOT NULL,
  `CODE` varchar(50) DEFAULT NULL,
  `NAME` varchar(100) DEFAULT NULL,
  `DESCRIPTION` varchar(250) DEFAULT NULL,
  `PARENT_ID` int(4) DEFAULT NULL,
  `ACTIVE` int(1) DEFAULT '1',
  `CREATED_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `MODULE_PRIVILEGES` */

CREATE TABLE `MODULE_PRIVILEGES` (
  `ID` int(18) NOT NULL,
  `MODULE_ID` int(4) DEFAULT NULL,
  `PRIVILEGE_TYPE_ID` int(4) DEFAULT NULL,
  `ACTIVE` int(1) DEFAULT '1',
  `CREATED_DATE` date DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `PRIVILEGE_TYPE` */

CREATE TABLE `PRIVILEGE_TYPE` (
  `ID` int(4) NOT NULL,
  `NAME` varchar(100) NOT NULL,
  `ACTIVE` int(1) NOT NULL DEFAULT '1',
  `DESCRIPTION` varchar(250) DEFAULT NULL,
  `CREATED_DATE` date DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `STUDENT` */

CREATE TABLE `STUDENT` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `BIOMETRIC_ID` varchar(100) DEFAULT NULL,
  `ROLL_NO` int(11) NOT NULL,
  `USER_ID` int(11) DEFAULT NULL,
  `GUARDIAN_USER_ID` int(11) DEFAULT NULL,
  `IS_ENROLLED` int(11) DEFAULT NULL,
  `ACTIVE` int(11) DEFAULT NULL,
  `CREATED_BY` int(11) DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT NULL,
  `MODIFIED_BY` int(11) DEFAULT NULL,
  `MODIFIED_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `STUDENT_FK1` (`USER_ID`),
  CONSTRAINT `STUDENT_FK1` FOREIGN KEY (`USER_ID`) REFERENCES `USER_MASTER` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=26 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `STUDENT_ADMISSION_DETAILS` */

CREATE TABLE `STUDENT_ADMISSION_DETAILS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `STUDENT_ID` int(11) DEFAULT NULL,
  `BRANCH_ID` int(11) DEFAULT NULL,
  `ACADEMIC_YEARID` int(11) DEFAULT NULL,
  `DATE_OF_ADMISSION` date DEFAULT NULL,
  `ADMISSION_TYPEID` int(11) DEFAULT NULL,
  `CREATED_DATE` date DEFAULT NULL,
  `CREATED_BY` int(11) DEFAULT NULL,
  `MODIFIED_DATE` date DEFAULT NULL,
  `MODIFIED_BY` int(11) DEFAULT NULL,
  `ACTIVE` int(1) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `STUDENT_ADMISSION_DETAILS_FK1` (`STUDENT_ID`),
  KEY `STUDENT_ADMISSION_DETAILS_FK2` (`BRANCH_ID`),
  KEY `STUDENT_ADMISSION_DETAILS_FK3` (`ADMISSION_TYPEID`),
  KEY `STUDENT_ADMISSION_DETAILS_FK4` (`ACADEMIC_YEARID`),
  CONSTRAINT `STUDENT_ADMISSION_DETAILS_FK1` FOREIGN KEY (`STUDENT_ID`) REFERENCES `STUDENT` (`ID`),
  CONSTRAINT `STUDENT_ADMISSION_DETAILS_FK2` FOREIGN KEY (`BRANCH_ID`) REFERENCES `CUSTOMER_BRANCHES` (`ID`),
  CONSTRAINT `STUDENT_ADMISSION_DETAILS_FK3` FOREIGN KEY (`ADMISSION_TYPEID`) REFERENCES `ADMISSION_TYPE` (`ID`),
  CONSTRAINT `STUDENT_ADMISSION_DETAILS_FK4` FOREIGN KEY (`ACADEMIC_YEARID`) REFERENCES `ACADEMIC_YEARS` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `STUDENT_COURSES` */

CREATE TABLE `STUDENT_COURSES` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `STUDENT_ID` int(11) DEFAULT NULL,
  `BRANCH_COURSES_ID` int(11) DEFAULT NULL,
  `COURSE_FEE_AMOUNT` decimal(10,0) DEFAULT NULL,
  `DISCOUNT_ALLOWED` int(11) DEFAULT NULL,
  `DISCOUNTED_FEE_AMOUNT` decimal(10,0) DEFAULT NULL,
  `ACTIVE` int(11) DEFAULT NULL,
  `CREATED_DATE` date DEFAULT NULL,
  `CREATED_BY` int(11) DEFAULT NULL,
  `MODIFIED_DATE` date DEFAULT NULL,
  `MODIFIED_BY` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `STUDENT_COURSES_FK1` (`STUDENT_ID`),
  KEY `STUDENT_COURSES_FK2` (`BRANCH_COURSES_ID`),
  CONSTRAINT `STUDENT_COURSES_FK1` FOREIGN KEY (`STUDENT_ID`) REFERENCES `STUDENT` (`ID`),
  CONSTRAINT `STUDENT_COURSES_FK2` FOREIGN KEY (`BRANCH_COURSES_ID`) REFERENCES `BRANCH_COURSES` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `STUDENT_DETAILS` */

CREATE TABLE `STUDENT_DETAILS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `STUDENT_ID` int(11) DEFAULT NULL,
  `ACADEMIC_INSTITUE_ID` int(11) DEFAULT NULL,
  `STUDENT_IMAGE_PATH` varchar(150) DEFAULT NULL,
  `FATHER_FIRST_NAME` varchar(150) DEFAULT NULL,
  `FATHER_MIDDLE_NAME` varchar(150) DEFAULT NULL,
  `FATHER_LAST_NAME` varchar(150) DEFAULT NULL,
  `FATHER_CONTACTNO` int(11) DEFAULT NULL,
  `FATHER_ANUAL_INCOME` decimal(10,0) DEFAULT NULL,
  `FATHER_QUALIFICATION` varchar(150) DEFAULT NULL,
  `FATHER_OCCUPATION` varchar(100) DEFAULT NULL,
  `MOTHER_FIRST_NAME` varchar(150) DEFAULT NULL,
  `MOTHER_MIDDLE_NAME` varchar(150) DEFAULT NULL,
  `MOTHER_LAST_NAME` varchar(150) DEFAULT NULL,
  `MOTHER_QUALIFICATION` varchar(150) DEFAULT NULL,
  `MOTHER_OCCUPATION` varchar(100) DEFAULT NULL,
  `MOTHER_CONTACTNO` int(11) DEFAULT NULL,
  `MOTHER_ANUAL_INCOME` decimal(10,0) DEFAULT NULL,
  `DATE_OF_BIRTH` datetime DEFAULT NULL,
  `STUDENT_QUALIFICATION` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `CREATED_BY` int(11) DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT NULL,
  `MODIFIED_BY` int(11) DEFAULT NULL,
  `MODIFIED_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `STUDENT_DETAILS_FK1` (`STUDENT_ID`),
  CONSTRAINT `STUDENT_DETAILS_FK1` FOREIGN KEY (`STUDENT_ID`) REFERENCES `STUDENT` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `USER_DETAILS` */

CREATE TABLE `USER_DETAILS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `USER_ID` int(11) NOT NULL,
  `PASSWORD_EXPIRATION_DATE` datetime DEFAULT NULL,
  `LANGUAGE_ID` int(11) DEFAULT NULL,
  `PAGE_SIZE` int(4) DEFAULT NULL,
  `PWD_VALIDATION_CODE` varchar(100) DEFAULT NULL,
  `IS_TEMPORARYPASSWORD` int(2) DEFAULT NULL,
  `LAST_LOGIN_DATE` date DEFAULT NULL,
  `LOCK_ATTEMPTS` int(2) DEFAULT NULL,
  `CREATED_BY` int(11) DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT NULL,
  `MODIFIED_BY` int(11) DEFAULT NULL,
  `MODIFIED_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `USER_DETAILS_FK1` (`USER_ID`),
  KEY `USER_DETAILS_FK2` (`LANGUAGE_ID`),
  CONSTRAINT `USER_DETAILS_FK1` FOREIGN KEY (`USER_ID`) REFERENCES `USER_MASTER` (`ID`),
  CONSTRAINT `USER_DETAILS_FK2` FOREIGN KEY (`LANGUAGE_ID`) REFERENCES `LANGUAGE_MASTER` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `USER_DETAILS_AUDIT` */

CREATE TABLE `USER_DETAILS_AUDIT` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `USER_DETAILS_ID` int(11) NOT NULL,
  `USER_ID` int(11) NOT NULL,
  `PASSWORD_EXPIRATION_DATE` datetime DEFAULT NULL,
  `LANGUAGE_ID` int(11) DEFAULT NULL,
  `PAGE_SIZE` int(4) DEFAULT NULL,
  `PWD_VALIDATION_CODE` varchar(100) DEFAULT NULL,
  `IS_TEMPORARYPASSWORD` int(2) DEFAULT NULL,
  `LAST_LOGIN_DATE` date DEFAULT NULL,
  `LOCK_ATTEMPTS` int(2) DEFAULT NULL,
  `CREATED_BY` int(11) DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT NULL,
  `MODIFIED_BY` int(11) DEFAULT NULL,
  `MODIFIED_DATE` datetime DEFAULT NULL,
  `OPERATION` int(1) DEFAULT NULL,
  `OPERATION_DATE` datetime DEFAULT NULL,
  `IP_ADDRESS` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `USER_DETAILS_AUDIT_FK1` (`USER_ID`),
  KEY `USER_DETAILS_AUDIT_FK2` (`LANGUAGE_ID`),
  KEY `USER_DETAILS_AUDIT_FK3` (`USER_DETAILS_ID`),
  CONSTRAINT `USER_DETAILS_AUDIT_FK1` FOREIGN KEY (`USER_ID`) REFERENCES `USER_MASTER` (`ID`),
  CONSTRAINT `USER_DETAILS_AUDIT_FK2` FOREIGN KEY (`LANGUAGE_ID`) REFERENCES `LANGUAGE_MASTER` (`ID`),
  CONSTRAINT `USER_DETAILS_AUDIT_FK3` FOREIGN KEY (`USER_DETAILS_ID`) REFERENCES `USER_DETAILS` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `USER_LOGIN_DETAILS` */

CREATE TABLE `USER_LOGIN_DETAILS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `USER_ID` int(11) DEFAULT NULL,
  `LOGIN_DATE` datetime DEFAULT NULL,
  `CUSTOMER_ID` int(11) DEFAULT NULL,
  `USER_BROWSER_SYSTEM_DETAILS` json DEFAULT NULL,
  `LOG_OUT` datetime DEFAULT NULL,
  `IS_SUCCESS` int(2) DEFAULT NULL,
  `CREATED_BY` int(11) DEFAULT NULL,
  `CREATED_DATE` date DEFAULT NULL,
  `MODIFIED_BY` int(11) DEFAULT NULL,
  `MODIFIED_DATE` datetime DEFAULT NULL,
  `LOGIN_REFRESH_TOKEN` varchar(2000) DEFAULT NULL,
  `LOGIN_TOKEN` varchar(2000) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=89 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `USER_MASTER` */

CREATE TABLE `USER_MASTER` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `LOGIN_ID` varchar(150) NOT NULL,
  `PASSWORD` varchar(250) DEFAULT NULL,
  `FIRST_NAME` varchar(150) DEFAULT NULL,
  `MIDDLE_NAME` varchar(150) DEFAULT NULL,
  `LAST_NAME` varchar(150) DEFAULT NULL,
  `PRIMARY_CONTACTNO` int(11) DEFAULT NULL,
  `USER_TYPE_ID` int(11) DEFAULT NULL,
  `ACTIVE` int(1) DEFAULT NULL,
  `CUSTOMER_ID` int(11) DEFAULT NULL,
  `CONTACT_NO` json DEFAULT NULL,
  `ADDRESS` json DEFAULT NULL,
  `NOTIFICATION_ID` varchar(150) DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT NULL,
  `CREATED_BY` int(11) DEFAULT NULL,
  `MODIFIED_DATE` datetime DEFAULT NULL,
  `MODIFIED_BY` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `USER_MASTER_FK1` (`USER_TYPE_ID`),
  KEY `USER_MASTER_FK2` (`CUSTOMER_ID`),
  CONSTRAINT `USER_MASTER_FK1` FOREIGN KEY (`USER_TYPE_ID`) REFERENCES `USER_TYPE` (`ID`),
  CONSTRAINT `USER_MASTER_FK2` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `CUSTOMER_MASTER` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=65 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `USER_MASTER_AUDIT` */

CREATE TABLE `USER_MASTER_AUDIT` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `USER_ID` int(11) DEFAULT NULL,
  `LOGIN_ID` varchar(150) DEFAULT NULL,
  `PASSWORD` varchar(250) DEFAULT NULL,
  `FIRST_NAME` varchar(150) DEFAULT NULL,
  `MIDDLE_NAME` varchar(150) DEFAULT NULL,
  `LAST_NAME` varchar(150) DEFAULT NULL,
  `USER_TYPE_ID` int(11) DEFAULT NULL,
  `CUSTOMER_ID` int(11) DEFAULT NULL,
  `CONTACT_NO` json DEFAULT NULL,
  `ADDRESS` json DEFAULT NULL,
  `NOTIFICATION_ID` varchar(150) DEFAULT NULL,
  `IP_ADDRESS` varchar(150) DEFAULT NULL,
  `OS_USER` varchar(150) DEFAULT NULL,
  `OPERATION` int(2) DEFAULT NULL,
  `OPERATION_DATE` datetime DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT NULL,
  `CREATED_BY` int(11) DEFAULT NULL,
  `MODIFIED_DATE` datetime DEFAULT NULL,
  `MODIFIED_BY` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `USER_TYPE` */

CREATE TABLE `USER_TYPE` (
  `ID` int(11) NOT NULL,
  `name` varchar(150) DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `VEDIC_COURSES_MASTER` */

CREATE TABLE `VEDIC_COURSES_MASTER` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(250) DEFAULT NULL,
  `COURSE_TYPE_ID` int(11) DEFAULT NULL,
  `COURSE_DESCRIPTION` varchar(250) DEFAULT NULL,
  `COURSE_DURATION_MONTHS` varchar(250) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `COURSES_FK` (`COURSE_TYPE_ID`),
  CONSTRAINT `COURSES_FK` FOREIGN KEY (`COURSE_TYPE_ID`) REFERENCES `VEDIC_COURSE_TYPE` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `VEDIC_COURSE_HIERACHY` */

CREATE TABLE `VEDIC_COURSE_HIERACHY` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(250) DEFAULT NULL,
  `PARENT_ID` int(11) DEFAULT NULL,
  `ACTIVE` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `COURSES_STRUCTURE_HIERACHY_FK1` (`PARENT_ID`),
  CONSTRAINT `COURSES_STRUCTURE_HIERACHY_FK1` FOREIGN KEY (`PARENT_ID`) REFERENCES `VEDIC_COURSE_HIERACHY` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `VEDIC_COURSE_HIERACHY_LEVEL` */

CREATE TABLE `VEDIC_COURSE_HIERACHY_LEVEL` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(250) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `VEDIC_COURSE_HIERACHY_MAPPING` */

CREATE TABLE `VEDIC_COURSE_HIERACHY_MAPPING` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `COURSE_ID` int(11) NOT NULL,
  `COURSE_HIERACHY_ID` int(11) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `VEDIC_COURSE_HIERACHY_MAPPING_FK1` (`COURSE_HIERACHY_ID`),
  KEY `VEDIC_COURSE_HIERACHY_MAPPING_FK2` (`COURSE_ID`),
  CONSTRAINT `VEDIC_COURSE_HIERACHY_MAPPING_FK1` FOREIGN KEY (`COURSE_HIERACHY_ID`) REFERENCES `VEDIC_COURSE_HIERACHY` (`ID`),
  CONSTRAINT `VEDIC_COURSE_HIERACHY_MAPPING_FK2` FOREIGN KEY (`COURSE_ID`) REFERENCES `VEDIC_COURSES_MASTER` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `VEDIC_COURSE_TYPE` */

CREATE TABLE `VEDIC_COURSE_TYPE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `COURSE_TYPE_NAME` varchar(250) DEFAULT NULL,
  `EDUCATIONAL_INSTITUTIONS_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `COURSE_TYPE_FK` (`EDUCATIONAL_INSTITUTIONS_ID`),
  CONSTRAINT `COURSE_TYPE_FK` FOREIGN KEY (`EDUCATIONAL_INSTITUTIONS_ID`) REFERENCES `VEDIC_EDUCATIONAL_INSTITUTIONS` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `VEDIC_EDUCATIONAL_INSTITUTIONS` */

CREATE TABLE `VEDIC_EDUCATIONAL_INSTITUTIONS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `INSTITUTION_TYPE_ID` int(11) DEFAULT NULL,
  `NAME` varchar(250) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `EDUCATIONAL_INSTITUTIONS_FK` (`INSTITUTION_TYPE_ID`),
  CONSTRAINT `EDUCATIONAL_INSTITUTIONS_FK` FOREIGN KEY (`INSTITUTION_TYPE_ID`) REFERENCES `VEDIC_INSTITUTION_TYPE` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `VEDIC_INSTITUTION_TYPE` */

CREATE TABLE `VEDIC_INSTITUTION_TYPE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(250) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `VEDIC_ROLES_PRIVILEGES` */

CREATE TABLE `VEDIC_ROLES_PRIVILEGES` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ROLE_ID` int(11) DEFAULT NULL,
  `PRIVILEG_TYPE_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/* Procedure structure for procedure `SP_Get_All_Customers` */

DELIMITER $$

/*!50003 CREATE PROCEDURE `SP_Get_All_Customers`()
BEGIN
    SELECT * FROM CUSTOMER_MASTER;
	

	END */$$
DELIMITER ;

/* Procedure structure for procedure `SP_INSERT_CUSTOMER` */

DELIMITER $$

/*!50003 CREATE PROCEDURE `SP_INSERT_CUSTOMER`(
        IN  p_NAME                    VARCHAR(150), 
        IN  p_CODE                    VARCHAR(150)   
         )
BEGIN

    INSERT INTO CUSTOMER_MASTER(CODE ,NAME )VALUES(p_CODE , p_NAME) ; 
	END */$$
DELIMITER ;

/* Procedure structure for procedure `SP_INSERT_USER_DETAILS` */

DELIMITER $$

/*!50003 CREATE PROCEDURE `SP_INSERT_USER_DETAILS`(
	
IN	P_USER_ID INT (11),
IN	P_PASSWORD_EXPIRATION_DATE DATETIME ,
IN	P_LANGUAGE_ID INT (11),
IN	P_PAGE_SIZE INT (4),
IN	P_PWD_VALIDATION_CODE VARCHAR (400),
IN	P_IS_TEMPORARYPASSWORD INT (2),
IN	P_LAST_LOGIN_DATE DATE ,
IN	P_LOCK_ATTEMPTS INT (2),
IN	P_CREATED_BY INT (11),
IN	P_CREATED_DATE DATETIME ,
IN	P_MODIFIED_BY INT (11),
IN	P_MODIFIED_DATE DATETIME ,
OUT	P_USER_DETAIL_OUT_ID INT (11)
)
BEGIN
START TRANSACTION;
	   INSERT INTO USER_DETAILS
	   (
	USER_ID ,
	PASSWORD_EXPIRATION_DATE  ,
	LANGUAGE_ID ,
	PAGE_SIZE ,
	PWD_VALIDATION_CODE ,
	IS_TEMPORARYPASSWORD ,
	LAST_LOGIN_DATE  ,
	LOCK_ATTEMPTS ,
	CREATED_BY ,
	CREATED_DATE  ,
	MODIFIED_BY ,
	MODIFIED_DATE 
	   )
	   VALUES(
	P_USER_ID ,
	P_PASSWORD_EXPIRATION_DATE  ,
	P_LANGUAGE_ID ,
	P_PAGE_SIZE,
	P_PWD_VALIDATION_CODE ,
	P_IS_TEMPORARYPASSWORD ,
	P_LAST_LOGIN_DATE  ,
	P_LOCK_ATTEMPTS ,
	P_CREATED_BY ,
	P_CREATED_DATE  ,
	P_MODIFIED_BY ,
	P_MODIFIED_DATE 		   );
   
SET P_USER_DETAIL_OUT_ID= LAST_INSERT_ID(USER_DETAILS) ;
	END */$$
DELIMITER ;

/* Procedure structure for procedure `SP_INSERT_STUDENT` */

DELIMITER $$

/*!50003 CREATE PROCEDURE `SP_INSERT_STUDENT`(
  
IN P_USER_ID int (11),
IN P_ROLL_NO  INT(11),
IN P_GUARDIAN_USER_ID int (11),
IN P_IS_ENROLLED int (11),
IN P_ACTIVE int (11),
IN P_CREATED_BY int (11),
IN P_CREATED_DATE DATETIME ,
IN P_MODIFIED_BY int (11),
IN P_MODIFIED_DATE datetIME,
 OUT P_OUT_STUDENT_ID INT (11)
)
BEGIN
START TRANSACTION;
	   insert into STUDENT
	   (
	  USER_ID ,
	  ROLL_NO,
	 GUARDIAN_USER_ID ,
	 IS_ENROLLED ,
	 ACTIVE ,
	 CREATED_BY ,
	 CREATED_DATE  ,
	 MODIFIED_BY ,
	 MODIFIED_DATE 
	   )
	   VALUES(
	 P_USER_ID ,
	 P_ROLL_NO,
	 P_GUARDIAN_USER_ID ,
	 P_IS_ENROLLED ,
	 P_ACTIVE ,
	 P_CREATED_BY ,
	 P_CREATED_DATE  ,
	 P_MODIFIED_BY ,
	 P_MODIFIED_DATE 
	   );
   
SET P_OUT_STUDENT_ID= last_insert_id() ;
	END */$$
DELIMITER ;

/* Procedure structure for procedure `DEV_TEST` */

DELIMITER $$

/*!50003 CREATE PROCEDURE `DEV_TEST`(IN P_STUDENT_OBJECT JSON,
OUT P_OUT_FLAG VARCHAR(50)    
    )
BEGIN
    DECLARE    J_V_CUSTOMERID VARCHAR(40);    
    DECLARE    J_V_STUDENT_LOGIN VARCHAR(150);
    DECLARE    J_V_STUDENT_LOGIN_PASSWORD VARCHAR(250);
    DECLARE    J_V_STUDENT_ROLLNO INT(11);
    DECLARE    J_V_STUDENT_FIRST_NAME VARCHAR(150);
    DECLARE    J_V_STUDENT_MIDDLE_NAME VARCHAR(150);
    DECLARE    J_V_STUDENT_LAST_NAME VARCHAR(150);
    DECLARE    J_V_STUDENT_NOTIFICATION_ID VARCHAR(150) ;
    DECLARE    J_V_STUDENT_ADDRESS JSON ;
    DECLARE    J_V_STUDENT_CONTACTNO INT(11) ;
    DECLARE    J_V_IS_ENROLLED INT(11);
    DECLARE    J_V_GUARDIAN_LOGIN VARCHAR(150) ;
    DECLARE    J_V_GUARDIAN_LOGIN_PASSWORD VARCHAR(250);
    DECLARE    J_V_GUARDIAN_FIRST_NAME VARCHAR(150);
    DECLARE    J_V_GUARDIAN_MIDDLE_NAME VARCHAR(150);
    DECLARE    J_V_GUARDIAN_LAST_NAME VARCHAR(150) ;
    DECLARE    J_V_GUARDIAN_NOTIFICATION_ID     VARCHAR(150) ;
    DECLARE    J_V_GUARDIAN_ADDRESS JSON ;
    DECLARE    J_V_GUARDIAN_CONTACTNO JSON;
    DECLARE    J_V_FATHER_FIRST_NAME VARCHAR(150) ;
    DECLARE    J_V_FATHER_MIDDLE_NAME VARCHAR(150) ;
    DECLARE    J_V_FATHER_LAST_NAME VARCHAR(150) ;
    DECLARE    J_V_FATHER_OCCUPATION VARCHAR(150) ;
    DECLARE    J_V_FATHER_QUALIFICATION VARCHAR(150) ;
    DECLARE    J_V_FATHER_ANUAL_INCOME DECIMAL ;
    DECLARE    J_V_FATHER_NOTIFICATION_ID     VARCHAR(150) ;
    DECLARE    J_V_FATHER_ADDRESS JSON;
    DECLARE    J_V_FATHER_CONTACTNO INT ;
    DECLARE    J_V_MOTHER_FIRST_NAME VARCHAR(150) ;
    DECLARE    J_V_MOTHER_MIDDLE_NAME VARCHAR(150) ;
    DECLARE    J_V_MOTHER_LAST_NAME VARCHAR(150);
    DECLARE    J_V_MOTHER_OCCUPATION VARCHAR(150) ;
    DECLARE    J_V_MOTHER_QUALIFICATION VARCHAR(150) ;
    DECLARE    J_V_STUDENT_GENDER VARCHAR(2) ;
    DECLARE    J_V_STUDENT_IMAGE_PATH VARCHAR(150) ;
    DECLARE    J_V_MOTHER_ANUAL_INCOME DECIMAL ;
    DECLARE    J_V_MOTHER_NOTIFICATION_ID  VARCHAR(150)  ;
    DECLARE    J_V_MOTHER_ADDRESS JSON  ;
    DECLARE    J_V_MOTHER_CONTACTNO INT;
    DECLARE    J_V_CREATED_BY INT(11);
    DECLARE    J_V_CREATED_DATE DATETIME ;
    DECLARE   J_V_STUDENT_ACADEMIC_INSTITUTE VARCHAR(150);
    DECLARE   J_V_STUDENT_DATE_OF_BIRTH DATETIME;
    DECLARE   J_V_STUDENT_QUALIFICATION VARCHAR(150);
    #Internal Varialbles 
    DECLARE    V_MODIFIED_BY INT(11) ;
    DECLARE    V_MODIFIED_DATE DATETIME ;
    DECLARE    V_ACTIVE INT(11);
    DECLARE    V_USERTYPEID_FOR_STUDENT INT(11);
    DECLARE    V_USERTYPEID_FOR_GUARDIAN INT(11);
    #OUTPUT ID Variables
    DECLARE    V_USER_ID_FOR_STUDENT INT(11);
    DECLARE    V_USER_ID_FOR_GUARDIAN INT(11);
    DECLARE    V_OUT_USER_ID INT(11);
    DECLARE    V_STUDENT_ID INT(11);
    DECLARE    V_STUDENT_DETAIL_ID INT(11);

		SELECT  CUSTOMERID,
		        STUDENT_LOGIN ,
		        STUDENT_ROLLNO,
		        STUDENT_LOGIN_PASSWORD,
			STUDENT_FIRST_NAME ,
			STUDENT_MIDDLE_NAME ,
			STUDENT_LAST_NAME ,
			STUDENT_NOTIFICATION_ID ,
			STUDENT_ADDRESS ,
			STUDENT_CONTACTNO ,
			STUDENT_ACADEMIC_INSTITUTE,
			STUDENT_QUALIFICATION,
			STUDENT_DATE_OF_BIRTH,
			STUDENT_GENDER,
			STUDENT_IMAGE_PATH,
			IS_ENROLLED ,
			GUARDIAN_LOGIN ,
			GUARDIAN_LOGIN_PASSWORD,
			GUARDIAN_FIRST_NAME ,
			GUARDIAN_MIDDLE_NAME ,
			GUARDIAN_LAST_NAME ,
			GUARDIAN_NOTIFICATION_ID ,
			GUARDIAN_ADDRESS ,
			GUARDIAN_CONTACTNO ,
			FATHER_FIRST_NAME ,
			FATHER_MIDDLE_NAME ,
			FATHER_LAST_NAME ,
			FATHER_OCCUPATION ,
			FATHER_QUALIFICATION,
			FATHER_ANUAL_INCOME,
			FATHER_NOTIFICATION_ID ,
			FATHER_ADDRESS ,
			FATHER_CONTACTNO ,
			MOTHER_FIRST_NAME ,
			MOTHER_MIDDLE_NAME ,
			MOTHER_LAST_NAME ,
			MOTHER_OCCUPATION ,
			MOTHER_QUALIFICATION,
			MOTHER_ANUAL_INCOME ,
			MOTHER_NOTIFICATION_ID  ,
			MOTHER_ADDRESS ,
			MOTHER_CONTACTNO ,
			CREATED_BY,
			CREATED_DATE
			INTO 
			J_V_CUSTOMERID,
			J_V_STUDENT_LOGIN ,
			J_V_STUDENT_ROLLNO,
			J_V_STUDENT_LOGIN_PASSWORD,
			J_V_STUDENT_FIRST_NAME ,
			J_V_STUDENT_MIDDLE_NAME ,
			J_V_STUDENT_LAST_NAME ,
			J_V_STUDENT_NOTIFICATION_ID ,
			J_V_STUDENT_ADDRESS ,
			J_V_STUDENT_CONTACTNO ,
			J_V_STUDENT_ACADEMIC_INSTITUTE,
			J_V_STUDENT_QUALIFICATION,
			J_V_STUDENT_DATE_OF_BIRTH,
			J_V_STUDENT_GENDER,
			J_V_STUDENT_IMAGE_PATH,
			J_V_IS_ENROLLED ,
			J_V_GUARDIAN_LOGIN ,
			J_V_GUARDIAN_LOGIN_PASSWORD,
			J_V_GUARDIAN_FIRST_NAME ,
			J_V_GUARDIAN_MIDDLE_NAME ,
			J_V_GUARDIAN_LAST_NAME ,
			J_V_GUARDIAN_NOTIFICATION_ID ,
			J_V_GUARDIAN_ADDRESS ,
			J_V_GUARDIAN_CONTACTNO ,
			J_V_FATHER_FIRST_NAME ,
			J_V_FATHER_MIDDLE_NAME ,
			J_V_FATHER_LAST_NAME ,
			J_V_FATHER_OCCUPATION ,
			J_V_FATHER_QUALIFICATION,
			J_V_FATHER_ANUAL_INCOME,
			J_V_FATHER_NOTIFICATION_ID ,
			J_V_FATHER_ADDRESS ,
			J_V_FATHER_CONTACTNO ,
			J_V_MOTHER_FIRST_NAME ,
			J_V_MOTHER_MIDDLE_NAME ,
			J_V_MOTHER_LAST_NAME ,
			J_V_MOTHER_OCCUPATION ,
			J_V_MOTHER_QUALIFICATION,
			J_V_MOTHER_ANUAL_INCOME ,
			J_V_MOTHER_NOTIFICATION_ID  ,
			J_V_MOTHER_ADDRESS ,
			J_V_MOTHER_CONTACTNO  ,
			J_V_CREATED_BY,
			J_V_CREATED_DATE
			FROM
		 JSON_TABLE('{
		"Customerid": "1",
		"Studentloginid": "Dev16nov19",
		               "Rollno": "12",
		               "Studentloginpassword": "abc",
		               "Studentfirstname": "Dev",
				"Studentmiddlename": "kumt",
				"Studentlastname": "Tanwar",
				"Studentnotificationid": "dev.sanga@gmail.com",
				"Studentaddress": "{}",
				"Studentcontactno": "",
				"Studentacademicinstitute": "",
				"StudentQualification": "",
				"Studentdateofbirth": "",
				"Gender": "M",
				"Studentimagepath": "",
				"Isenrolled": "0",
				"Guardianloginid": "DWARKA123",
				"Guardianpassword": "abc",
				"Guardianfirstname": "DWARKA",
				"Guardianmiddlename": "",
				"Guardianlastname": "TANWAR",
				"Guardiannotificationid": "32",
				"Guardianaddress": "{}",
				"Guardiancontactno": "",
				"Fatherfirstname": "DWARKA",
				"Fathermiddlename": "",
				"Fatherlastname": "TANWAR",
				"Fathernotificationid": "dev.sanga@gmail.com",
				"Fathercontactno": "",
				"FatherQualification": "BCA",
				"FatherOccupation": "RETD",
				"FatherAnualIncome": "2345",
				"Fatheraddress": "{}",
				"Motherfirstname": "SHOBHA",
				"Mothermiddlename": "",
				"Motherlastname": "TANWAR",
				"Mothernotificationid": "32",
				"Mothercontactno": "dev.sanga@gmail.com",
				"MotherQualification": "",
				"MotherOccupation": "",
				"MotherAnualIncome": "98765432",
				"Createddate": "",
				"Createdby": "1"
				
			  }', 
			  '$' COLUMNS (
            CUSTOMERID INT(11) PATH '$.Customerid' ,
	    STUDENT_LOGIN VARCHAR(150)  PATH '$.Studentloginid',
	    STUDENT_ROLLNO INT(11) PATH '$.Rollno' ,
	    STUDENT_LOGIN_PASSWORD VARCHAR(250)  PATH '$.Studentloginpassword',
            STUDENT_FIRST_NAME VARCHAR(150) PATH '$.Studentfirstname',
            STUDENT_MIDDLE_NAME VARCHAR(150) PATH '$.Studentmiddlename',
            STUDENT_LAST_NAME VARCHAR(150) PATH '$.Studentlastname', 
            STUDENT_NOTIFICATION_ID VARCHAR(150) PATH '$.Studentnotificationid', 
            STUDENT_ADDRESS JSON PATH '$.Studentaddress' ,
            STUDENT_CONTACTNO INT(11) PATH '$.Studentcontactno' ,
            STUDENT_ACADEMIC_INSTITUTE VARCHAR(150) PATH '$.Studentacademicinstitute', 
            STUDENT_QUALIFICATION VARCHAR(150) PATH '$.StudentQualification', 
            STUDENT_DATE_OF_BIRTH DATETIME PATH '$.Studentdateofbirth', 
            STUDENT_GENDER VARCHAR(2) PATH '$.Gender', 
            STUDENT_IMAGE_PATH VARCHAR(2) PATH '$.Studentimagepath', 
            IS_ENROLLED INT(11) PATH '$.Isenrolled' ,
            GUARDIAN_LOGIN VARCHAR(150)  PATH '$.Guardianloginid',
            GUARDIAN_LOGIN_PASSWORD VARCHAR(250)  PATH '$.Guardianloginpassword',
            GUARDIAN_FIRST_NAME VARCHAR(150) PATH '$.Guardianfirstname',
            GUARDIAN_MIDDLE_NAME VARCHAR(150) PATH '$.Guardianmiddlename',
            GUARDIAN_LAST_NAME VARCHAR(150) PATH '$.Guardianlastname',
            GUARDIAN_NOTIFICATION_ID     VARCHAR(150) PATH '$.Guardiannotificationid',
            GUARDIAN_ADDRESS JSON PATH '$.Guardianaddress' ,
            GUARDIAN_CONTACTNO JSON PATH '$.Guardiancontactno' ,
            FATHER_FIRST_NAME VARCHAR(150) PATH '$.Fatherfirstname',
            FATHER_MIDDLE_NAME VARCHAR(150) PATH '$.Fathermiddlename',
            FATHER_LAST_NAME VARCHAR(150) PATH '$.Fatherlastname',
            FATHER_OCCUPATION VARCHAR(150) PATH '$.FatherOccupation',
            FATHER_QUALIFICATION VARCHAR(150) PATH '$.FatherQualification',
            FATHER_ANUAL_INCOME DECIMAL PATH '$.FatherAnualIncome',
            FATHER_NOTIFICATION_ID     VARCHAR(150) PATH '$.Fathernotificationid',
            FATHER_ADDRESS JSON PATH '$.Fatheraddress' ,
            FATHER_CONTACTNO INT PATH '$.Fathercontactno' ,
            MOTHER_FIRST_NAME VARCHAR(150) PATH '$.Motherfirstname',
            MOTHER_MIDDLE_NAME VARCHAR(150) PATH '$.Mothermiddlename',
            MOTHER_LAST_NAME VARCHAR(150) PATH '$.Motherlastname',
            MOTHER_OCCUPATION VARCHAR(150) PATH '$.MotherOccupation',
            MOTHER_QUALIFICATION VARCHAR(150) PATH '$.MotherQualification',
            MOTHER_ANUAL_INCOME DECIMAL PATH '$.MotherAnualIncome',
            MOTHER_NOTIFICATION_ID     VARCHAR(150) PATH '$.Mothernotificationid',
            MOTHER_ADDRESS JSON PATH '$.Motheraddress' ,
            MOTHER_CONTACTNO INT PATH '$.Mothercontactno' ,
            CREATED_BY INT PATH '$.Createdby' ,
            CREATED_DATE DATETIME PATH '$.Createddate' 
							
						   )
				 ) STUDENT_DETAILS;
START TRANSACTION;
SET V_ACTIVE=1;
SET V_USERTYPEID_FOR_STUDENT=3;
SET V_USERTYPEID_FOR_GUARDIAN=4;
SET V_USER_ID_FOR_STUDENT=0; 
SET V_USER_ID_FOR_GUARDIAN  =0;
SET V_STUDENT_ID=0;
SET V_STUDENT_DETAIL_ID=0;
    #First Student is exits or not if not exists then create user first
	
        SELECT IFNULL(ID,0)  INTO V_USER_ID_FOR_STUDENT
        FROM USER_MASTER WHERE customer_id=J_V_CUSTOMERID AND LOGIN_ID=J_V_STUDENT_LOGIN;	
	
	IF V_USER_ID_FOR_STUDENT =0 THEN
		CALL SP_INSERT_USER_MASTER(        J_V_STUDENT_LOGIN 	,
                                           J_V_STUDENT_LOGIN_PASSWORD	,
                                           J_V_STUDENT_FIRST_NAME,
                                           J_V_STUDENT_MIDDLE_NAME 	,
                                           J_V_STUDENT_LAST_NAME 	,
			                    		   V_USERTYPEID_FOR_STUDENT	,
                                           V_ACTIVE	,
                                           J_V_CUSTOMERID	,
                                           J_V_STUDENT_CONTACTNO 	,
                                           J_V_STUDENT_ADDRESS 	,
                                           J_V_STUDENT_NOTIFICATION_ID 	,
                                           J_V_CREATED_DATE	,
                                           J_V_CREATED_BY	,
                                           V_MODIFIED_DATE	,
                                           V_MODIFIED_BY	,
                                           @V_USER_ID_FOR_STUDENT
									);
	END IF;
	
	
	#First Guardian is exists or not if not exists then create user first
	
	
	SELECT IFNULL(ID,0)  INTO V_USER_ID_FOR_GUARDIAN
        FROM USER_MASTER WHERE customer_id=J_V_CUSTOMERID AND LOGIN_ID=J_V_GUARDIAN_LOGIN;	
		IF V_USER_ID_FOR_GUARDIAN =0 THEN
				CALL SP_INSERT_USER_MASTER(J_V_GUARDIAN_LOGIN 	,
                                          J_V_GUARDIAN_LOGIN_PASSWORD	,
                                          J_V_GUARDIAN_FIRST_NAME,
                                          J_V_GUARDIAN_MIDDLE_NAME 	,
                                          J_V_GUARDIAN_LAST_NAME 	,
					  V_USERTYPEID_FOR_GUARDIAN	,
                                          V_ACTIVE	,
                                          J_V_CUSTOMERID	,
                                          J_V_GUARDIAN_CONTACTNO 	,
                                          J_V_GUARDIAN_ADDRESS 	,
                                          J_V_GUARDIAN_NOTIFICATION_ID 	,
                                          J_V_CREATED_DATE	,
                                          J_V_CREATED_BY	,
                                          V_MODIFIED_DATE	,
                                          V_MODIFIED_BY	,
                                          @V_USER_ID_FOR_GUARDIAN);
		END IF;
		
		
		#Check whether Student exists or not 
		SELECT IFNULL(ID,0)  INTO V_STUDENT_ID
        FROM STUDENT WHERE USER_ID=V_USER_ID_FOR_STUDENT ;	
		
		IF V_STUDENT_ID=0 then 
	
		CALL SP_INSERT_STUDENT
					(
			  
			V_USER_ID_FOR_STUDENT,
			J_V_STUDENT_ROLLNO,
			V_USER_ID_FOR_GUARDIAN,
			J_V_IS_ENROLLED,
			V_ACTIVE,
			J_V_CREATED_BY,
			J_V_CREATED_DATE ,
			V_MODIFIED_BY,
			V_MODIFIED_DATE,
			@V_STUDENT_ID
			);
	    END IF;	
 
		#Check whether Student exists or not 
		SELECT IFNULL(ID,0)  INTO V_STUDENT_DETAIL_ID
        FROM STUDENT_DETAILS WHERE STUDENT_ID=V_STUDENT_ID ;
 
     IF   	V_STUDENT_DETAIL_ID=0 THEN	
		CALL SP_INSERT_STUDENT_DETAILS(
		V_STUDENT_ID,
		J_V_STUDENT_ACADEMIC_INSTITUTE,
		J_V_STUDENT_IMAGE_PATH,
		J_V_FATHER_FIRST_NAME,
		J_V_FATHER_LAST_NAME,
		J_V_FATHER_CONTACTNO,
		J_V_FATHER_ANUAL_INCOME,
		J_V_FATHER_QUALIFICATION,
		J_V_FATHER_OCCUPATION,
		J_V_MOTHER_FIRST_NAME,
		J_V_MOTHER_LAST_NAME,
		J_V_MOTHER_QUALIFICATION,
		J_V_MOTHER_OCCUPATION,
		J_V_MOTHER_CONTACTNO,
		J_V_MOTHER_ANUAL_INCOME,
		J_V_STUDENT_DATE_OF_BIRTH ,
		J_V_STUDENT_QUALIFICATION,
		J_V_CREATED_BY,
		J_V_CREATED_DATE,
		V_MODIFIED_BY,
		V_MODIFIED_DATE ,
		@V_STUDENT_DETAIL_ID);

    END IF;
          COMMIT;
	END */$$
DELIMITER ;

/* Procedure structure for procedure `SP_TEST` */

DELIMITER $$

/*!50003 CREATE PROCEDURE `SP_TEST`(
        IN  p_NAME                    VARCHAR(150), 
        IN  p_CODE                    VARCHAR(150),
        OUT P_OUT_STUDENTID INT(11)  
         )
BEGIN

     insert into JAI_MAA_BHAWANI values('test',now());
    SET P_OUT_STUDENTID=12;
       
	END */$$
DELIMITER ;

/* Procedure structure for procedure `SP_INSERT_USER_MASTER` */

DELIMITER $$

/*!50003 CREATE PROCEDURE `SP_INSERT_USER_MASTER`(    
  IN P_LOGIN_ID varchar(150) ,
  IN P_PASSWORD varchar(250) ,
  IN P_FIRST_NAME varchar(150) ,
  IN P_MIDDLE_NAME varchar(150) ,
  IN P_LAST_NAME varchar(150) ,
  IN P_USER_TYPE_ID int(11) ,
  IN P_ACTIVE int(1) ,
  IN P_CUSTOMER_ID int(11) ,
  IN P_CONTACT_NO json ,
  IN P_ADDRESS json ,
  IN P_NOTIFICATION_ID varchar(150) ,
  IN P_CREATED_DATE datetime ,
  IN P_CREATED_BY int(11) ,
  IN P_MODIFIED_DATE datetime ,
  IN P_MODIFIED_BY int(11) ,
  IN P_PRIMARY_CONTACTNO INT,
  OUT P_OUT_USER_ID INT(11) 
  )
BEGIN
	  START TRANSACTION;
	  
		insert into USER_MASTER
		   (		 
		   LOGIN_ID  ,
		   PASSWORD  ,
		   FIRST_NAME  ,
		   MIDDLE_NAME ,
		   LAST_NAME  ,
		   USER_TYPE_ID  ,
		   PRIMARY_CONTACTNO,
		   ACTIVE  ,
		   CUSTOMER_ID  ,
		   CONTACT_NO  ,
		   ADDRESS  ,
		   NOTIFICATION_ID  ,
		   CREATED_DATE  ,
		   CREATED_BY  ,
		   MODIFIED_DATE  ,
		   MODIFIED_BY 
		   )
		   values
		   (
		
		   P_LOGIN_ID  ,
		   P_PASSWORD  ,
		   P_FIRST_NAME  ,
		   P_MIDDLE_NAME ,
		   P_LAST_NAME  ,
		   P_USER_TYPE_ID  ,
		   P_PRIMARY_CONTACTNO,
		   P_ACTIVE  ,
		   P_CUSTOMER_ID  ,
		   P_CONTACT_NO  ,
		   P_ADDRESS  ,
		   P_NOTIFICATION_ID  ,
		   P_CREATED_DATE  ,
		   P_CREATED_BY  ,
		   P_MODIFIED_DATE  ,
		   P_MODIFIED_BY );
		    #P_ID=last_insert_id(USER_MASTER);
		    SET P_OUT_USER_ID= LAST_INSERT_ID() ;

	END */$$
DELIMITER ;

/* Procedure structure for procedure `SP_INSERT_STUDENT_DETAILS` */

DELIMITER $$

/*!50003 CREATE PROCEDURE `SP_INSERT_STUDENT_DETAILS`(
in	P_STUDENT_ID int (11),
IN	P_STUDENT_ACADEMIC_INSTITUE_ID INT,
IN	P_STUDENT_IMAGE_PATH VARCHAR(150),
IN	P_FATHER_FIRST_NAME varchar (150),
IN	P_FATHER_MIDDLE_NAME VARCHAR (150),
IN	P_FATHER_LAST_NAME varchar (150),
IN	P_FATHER_CONTACTNO int (11),
IN      P_FATHER_ANUAL_INCOME DECIMAL,
IN	P_FATHER_QUALIFICATION varchar (150),
IN	P_FATHER_OCCUPATION varchar (150),
IN	P_MOTHER_FIRST_NAME varchar (150),
IN	P_MOTHER_MIDDLE_NAME VARCHAR (150),
IN	P_MOTHER_LAST_NAME varchar (150),
IN	P_MOTHER_QUALIFICATION varchar (150),
IN	P_MOTHER_OCCUPATION varchar (150),
IN	P_MOTHER_CONTACTNO int (11),
IN      P_MOTHER_ANUAL_INCOME DECIMAL,
IN	P_DATE_OF_BIRTH dateTIME ,
IN	P_QUALIFICATION varchar (150),
IN	P_CREATED_BY int (11),
IN	P_CREATED_DATE DATETIME ,
IN	P_MODIFIED_BY int (11),
IN	P_MODIFIED_DATE DATETIME ,
OUT	P_OUT_STUDENT_DETAIL_ID INT (11)
)
BEGIN
START TRANSACTION;
	   INSERT INTO STUDENT_DETAILS
	   (
	STUDENT_ID ,
	ACADEMIC_INSTITUE_ID,
	STUDENT_IMAGE_PATH,
	FATHER_FIRST_NAME ,
	FATHER_MIDDLE_NAME,
	FATHER_LAST_NAME ,
	FATHER_CONTACTNO ,
	FATHER_ANUAL_INCOME,
	FATHER_QUALIFICATION ,
	FATHER_OCCUPATION,
	MOTHER_FIRST_NAME,
	MOTHER_MIDDLE_NAME,
	MOTHER_LAST_NAME,
	MOTHER_QUALIFICATION,
	MOTHER_OCCUPATION ,
	MOTHER_CONTACTNO ,
	MOTHER_ANUAL_INCOME,
	DATE_OF_BIRTH  ,
	STUDENT_QUALIFICATION,
	CREATED_BY ,
	CREATED_DATE  ,
	MODIFIED_BY ,
	MODIFIED_DATE 
	   )
	   VALUES(
	P_STUDENT_ID ,
P_STUDENT_ACADEMIC_INSTITUE_ID ,
P_STUDENT_IMAGE_PATH,
	P_FATHER_FIRST_NAME ,
	P_FATHER_MIDDLE_NAME,
	P_FATHER_LAST_NAME ,
	P_FATHER_CONTACTNO ,
	P_FATHER_ANUAL_INCOME,
	P_FATHER_QUALIFICATION ,
	P_FATHER_OCCUPATION,
	P_MOTHER_FIRST_NAME,
	P_MOTHER_MIDDLE_NAME,
	P_MOTHER_LAST_NAME,
	P_MOTHER_QUALIFICATION,
	P_MOTHER_OCCUPATION ,
	P_MOTHER_CONTACTNO ,
	P_MOTHER_ANUAL_INCOME,
	P_DATE_OF_BIRTH  ,
	P_QUALIFICATION,
	P_CREATED_BY ,
	P_CREATED_DATE  ,
	P_MODIFIED_BY ,
	P_MODIFIED_DATE  );
   
SET P_OUT_STUDENT_DETAIL_ID= LAST_INSERT_ID() ;
	END */$$
DELIMITER ;

/* Procedure structure for procedure `SP_CREATE_STUDENT` */

DELIMITER $$

/*!50003 CREATE PROCEDURE `SP_CREATE_STUDENT`(IN P_STUDENT_OBJECT JSON,
OUT P_OUT_FLAG VARCHAR(50)    ,
out P_OUT_STUDENTID INT(11)
    )
BEGIN
#STUDENT
    DECLARE    J_V_CUSTOMERID VARCHAR(40);    
    DECLARE    J_V_STUDENT_LOGIN VARCHAR(150);
    DECLARE    J_V_STUDENT_LOGIN_PASSWORD VARCHAR(250);
    DECLARE    J_V_STUDENT_ROLLNO INT(11);
    DECLARE    J_V_STUDENT_FIRST_NAME VARCHAR(150);
    DECLARE    J_V_STUDENT_MIDDLE_NAME VARCHAR(150);
    DECLARE    J_V_STUDENT_LAST_NAME VARCHAR(150);
    DECLARE    J_V_STUDENT_NOTIFICATION_ID VARCHAR(150) ;
    DECLARE    J_V_STUDENT_ADDRESS JSON ;
    DECLARE    J_V_STUDENT_CONTACTNO JSON ;
    DECLARE    J_V_STUDENT_PRIMARY_CONTACTNO INT ;
    DECLARE    J_V_IS_ENROLLED INT(11);
    DECLARE    J_V_BRANCH_ID INT(11);
    
    DECLARE    J_V_GUARDIAN_LOGIN VARCHAR(150) ;
    DECLARE    J_V_GUARDIAN_LOGIN_PASSWORD VARCHAR(250);
    DECLARE    J_V_GUARDIAN_FIRST_NAME VARCHAR(150);
    DECLARE    J_V_GUARDIAN_MIDDLE_NAME VARCHAR(150);
    DECLARE    J_V_GUARDIAN_LAST_NAME VARCHAR(150) ;
    DECLARE    J_V_GUARDIAN_NOTIFICATION_ID     VARCHAR(150) ;
    DECLARE    J_V_GUARDIAN_ADDRESS JSON ;
    DECLARE    J_V_GUARDIAN_CONTACTNO JSON;
    DECLARE    J_V_GURARDIAN_PRIMARY_CONTACTNO INT;
    DECLARE    J_V_FATHER_FIRST_NAME VARCHAR(150) ;
    DECLARE    J_V_FATHER_MIDDLE_NAME VARCHAR(150) ;
    DECLARE    J_V_FATHER_LAST_NAME VARCHAR(150) ;
    DECLARE    J_V_FATHER_OCCUPATION VARCHAR(150) ;
    DECLARE    J_V_FATHER_QUALIFICATION VARCHAR(150) ;
    DECLARE    J_V_FATHER_ANUAL_INCOME DECIMAL ;
    DECLARE    J_V_FATHER_NOTIFICATION_ID     VARCHAR(150) ;
    DECLARE    J_V_FATHER_ADDRESS JSON;
    DECLARE    J_V_FATHER_CONTACTNO JSON ;
    DECLARE    J_V_FATHER_PRIMARY_CONTACTNO INT;
    DECLARE    J_V_MOTHER_FIRST_NAME VARCHAR(150) ;
    DECLARE    J_V_MOTHER_MIDDLE_NAME VARCHAR(150) ;
    DECLARE    J_V_MOTHER_LAST_NAME VARCHAR(150);
    DECLARE    J_V_MOTHER_OCCUPATION VARCHAR(150) ;
    DECLARE    J_V_MOTHER_QUALIFICATION VARCHAR(150) ;
    DECLARE    J_V_STUDENT_GENDER VARCHAR(2) ;
    DECLARE    J_V_STUDENT_IMAGE_PATH VARCHAR(150) ;
    DECLARE    J_V_MOTHER_ANUAL_INCOME DECIMAL ;
    DECLARE    J_V_MOTHER_NOTIFICATION_ID  VARCHAR(150)  ;
    DECLARE    J_V_MOTHER_ADDRESS JSON  ;
    DECLARE    J_V_MOTHER_CONTACTNO JSON;
    DECLARE     J_V_MOTHER_PRIMARY_CONTACTNO INT;
    DECLARE    J_V_CREATED_BY INT(11);
    DECLARE    J_V_CREATED_DATE DATETIME ;
    DECLARE   J_V_STUDENT_ACADEMIC_INSTITUTE VARCHAR(150);
    DECLARE   J_V_STUDENT_DATE_OF_BIRTH DATETIME;
    DECLARE   J_V_STUDENT_QUALIFICATION VARCHAR(150);
    
 
    #Internal Varialbles 
    DECLARE    V_MODIFIED_BY INT(11) ;
    DECLARE    V_MODIFIED_DATE DATETIME ;
    DECLARE    V_ACTIVE INT(11);
    DECLARE    V_USERTYPEID_FOR_STUDENT INT(11);
    DECLARE    V_USERTYPEID_FOR_GUARDIAN INT(11);
    #OUTPUT ID Variables
    DECLARE    V_USER_ID_FOR_STUDENT INT(11);
    DECLARE    V_USER_ID_FOR_GUARDIAN INT(11);
    DECLARE    V_OUT_USER_ID INT(11);
    DECLARE    V_STUDENT_ID INT(11);
    DECLARE    V_STUDENT_DETAIL_ID INT(11);

		SELECT  CUSTOMERID,
		        BRANCHID,
		        LOWER(STUDENT_LOGIN) STUDENT_LOGIN,
		        STUDENT_ROLLNO,
		        STUDENT_LOGIN_PASSWORD,
			STUDENT_FIRST_NAME ,
			STUDENT_MIDDLE_NAME ,
			STUDENT_LAST_NAME ,
			STUDENT_NOTIFICATION_ID ,
			STUDENT_ADDRESS ,
			STUDENT_CONTACTNO ,
			STUDENT_PRIMARY_CONTACTNO,
			ACADEMIC_INSTITUTE_ID,
			STUDENT_QUALIFICATION,
			STUDENT_DATE_OF_BIRTH,
			STUDENT_GENDER,
			STUDENT_IMAGE_PATH,
			IS_ENROLLED ,
			LOWER(GUARDIAN_LOGIN) GUARDIAN_LOGIN,
			GUARDIAN_LOGIN_PASSWORD,
			GUARDIAN_FIRST_NAME ,
			GUARDIAN_MIDDLE_NAME ,
			GUARDIAN_LAST_NAME ,
			GUARDIAN_NOTIFICATION_ID ,
			GUARDIAN_ADDRESS ,
			GUARDIAN_CONTACTNO ,
			GURARDIAN_PRIMARY_CONTACTNO,
			
			FATHER_FIRST_NAME ,
			FATHER_MIDDLE_NAME ,
			FATHER_LAST_NAME ,
			FATHER_OCCUPATION ,
			FATHER_QUALIFICATION,
			FATHER_ANUAL_INCOME,
			FATHER_NOTIFICATION_ID ,
			FATHER_ADDRESS ,
			FATHER_CONTACTNO ,
			FATHER_PRIMARY_CONTACTNO,
			MOTHER_FIRST_NAME ,
			MOTHER_MIDDLE_NAME ,
			MOTHER_LAST_NAME ,
			MOTHER_OCCUPATION ,
			MOTHER_QUALIFICATION,
			MOTHER_ANUAL_INCOME ,
			MOTHER_NOTIFICATION_ID  ,
			MOTHER_ADDRESS ,
			MOTHER_CONTACTNO ,
			MOTHER_PRIMARY_CONTACTNO,
			CREATED_BY,
			CREATED_DATE
			INTO 
			J_V_CUSTOMERID,
			J_V_BRANCH_ID,
			J_V_STUDENT_LOGIN ,
			J_V_STUDENT_ROLLNO,
			J_V_STUDENT_LOGIN_PASSWORD,
			J_V_STUDENT_FIRST_NAME ,
			J_V_STUDENT_MIDDLE_NAME ,
			J_V_STUDENT_LAST_NAME ,
			J_V_STUDENT_NOTIFICATION_ID ,
			J_V_STUDENT_ADDRESS ,
			J_V_STUDENT_CONTACTNO ,
			J_V_STUDENT_PRIMARY_CONTACTNO,
			J_V_STUDENT_ACADEMIC_INSTITUTE,
			J_V_STUDENT_QUALIFICATION,
			J_V_STUDENT_DATE_OF_BIRTH,
			J_V_STUDENT_GENDER,
			J_V_STUDENT_IMAGE_PATH,
			J_V_IS_ENROLLED ,
			J_V_GUARDIAN_LOGIN ,
			J_V_GUARDIAN_LOGIN_PASSWORD,
			J_V_GUARDIAN_FIRST_NAME ,
			J_V_GUARDIAN_MIDDLE_NAME ,
			J_V_GUARDIAN_LAST_NAME ,
			J_V_GUARDIAN_NOTIFICATION_ID ,
			J_V_GUARDIAN_ADDRESS ,
			J_V_GUARDIAN_CONTACTNO ,
			J_V_GURARDIAN_PRIMARY_CONTACTNO,
			J_V_FATHER_FIRST_NAME ,
			J_V_FATHER_MIDDLE_NAME ,
			J_V_FATHER_LAST_NAME ,
			J_V_FATHER_OCCUPATION ,
			J_V_FATHER_QUALIFICATION,
			J_V_FATHER_ANUAL_INCOME,
			J_V_FATHER_NOTIFICATION_ID ,
			J_V_FATHER_ADDRESS ,
			J_V_FATHER_CONTACTNO ,
			J_V_FATHER_PRIMARY_CONTACTNO,
			J_V_MOTHER_FIRST_NAME ,
			J_V_MOTHER_MIDDLE_NAME ,
			J_V_MOTHER_LAST_NAME ,
			J_V_MOTHER_OCCUPATION ,
			J_V_MOTHER_QUALIFICATION,
			J_V_MOTHER_ANUAL_INCOME ,
			J_V_MOTHER_NOTIFICATION_ID  ,
			J_V_MOTHER_ADDRESS ,
			J_V_MOTHER_CONTACTNO  ,
			J_V_MOTHER_PRIMARY_CONTACTNO,
			J_V_CREATED_BY,
			J_V_CREATED_DATE
			FROM
		 JSON_TABLE(P_STUDENT_OBJECT, 
			  '$' COLUMNS (
             CUSTOMERID INT(11) PATH '$.CustomerId' ,
            BRANCHID INT(11) PATH '$.BranchId' ,
            STUDENT_ROLLNO INT(11) PATH '$.RollNo' ,
            CREATED_BY INT PATH '$.CreatedBy' ,
            CREATED_DATE DATETIME PATH '$.CreatedDate' ,
            ACADEMIC_INSTITUTE_ID INT PATH '$.AcademicInstituteId' ,
            IS_ENROLLED INT(11) PATH '$.IsEnrolled' ,
            #STUDENT           
            STUDENT_LOGIN VARCHAR(150)  PATH '$.StudentDetails.LoginId',
	    STUDENT_LOGIN_PASSWORD VARCHAR(250)  PATH '$.StudentDetails.Password',
            STUDENT_FIRST_NAME VARCHAR(150) PATH '$.StudentDetails.FirstName',
            STUDENT_MIDDLE_NAME VARCHAR(150) PATH '$.StudentDetails.MiddleName',
            STUDENT_LAST_NAME VARCHAR(150) PATH '$.StudentDetails.LastName', 
            STUDENT_NOTIFICATION_ID VARCHAR(150) PATH '$.StudentDetails.NotificationId', 
            STUDENT_PRIMARY_CONTACTNO INT PATH '$.StudentDetails.PrimaryContact', 
            STUDENT_DATE_OF_BIRTH DATETIME PATH '$.StudentDetails.DateOfBirth', 
            STUDENT_GENDER VARCHAR(2) PATH '$.StudentDetails.Sex', 
            STUDENT_IMAGE_PATH VARCHAR(150) PATH '$.StudentDetails.ImageName', 
            STUDENT_ADDRESS JSON PATH '$.StudentDetails.Details.Address' ,
            STUDENT_CONTACTNO VARCHAR(500) PATH '$.StudentDetails.Details.ContactNumber' ,
            STUDENT_QUALIFICATION VARCHAR(150) PATH '$.StudentDetails.Details.Qualification', 
            STUDENT_ANNUAL_INCOME DECIMAL PATH '$.StudentDetails.Details.AnnualIncome', 
            STUDENT_OCCUPATION VARCHAR(150) PATH '$.StudentDetails.Details.Occupation',
            #FATHER
            FATHER_FIRST_NAME VARCHAR(150) PATH '$.StudentDetails.Father.FirstName',
            FATHER_MIDDLE_NAME VARCHAR(150) PATH '$.StudentDetails.Father.MiddleName',
            FATHER_LAST_NAME VARCHAR(150) PATH '$.StudentDetails.Father.LastName',
            FATHER_OCCUPATION VARCHAR(150) PATH '$.StudentDetails.Father.Occupation',
            FATHER_QUALIFICATION VARCHAR(150) PATH '$.StudentDetails.Father.Qualification',
            FATHER_ANUAL_INCOME DECIMAL PATH '$.StudentDetails.Father.AnnualIncome',
            FATHER_PRIMARY_CONTACTNO INT PATH '$.StudentDetails.Father.PrimaryContact' , 
            FATHER_NOTIFICATION_ID     VARCHAR(150) PATH '$.StudentDetails.Father.NotificationId',
            FATHER_ADDRESS JSON PATH '$.StudentDetails.Father.Address' ,
            FATHER_CONTACTNO JSON PATH '$.StudentDetails.Father.ContactNumber' ,
            FATHER_PRIMARY_NO INT PATH '$.StudentDetails.Father.PrimaryContact' ,
            #MOTHER
            MOTHER_FIRST_NAME VARCHAR(150) PATH '$.StudentDetails.Mother.FirstName',
            MOTHER_MIDDLE_NAME VARCHAR(150) PATH '$.StudentDetails.Mother.MiddleName',
            MOTHER_LAST_NAME VARCHAR(150) PATH '$.StudentDetails.Mother.LastName',
            MOTHER_OCCUPATION VARCHAR(150) PATH '$.StudentDetails.Mother.Occupation',
            MOTHER_QUALIFICATION VARCHAR(150) PATH '$.StudentDetails.Mother.Qualification',
            MOTHER_ANUAL_INCOME DECIMAL PATH '$.StudentDetails.Mother.AnnualIncome',
            MOTHER_NOTIFICATION_ID     VARCHAR(150) PATH '$.StudentDetails.Mother.NotificationId',
            MOTHER_ADDRESS JSON PATH '$.StudentDetails.Mother.Address' ,
            MOTHER_CONTACTNO JSON PATH '$.StudentDetails.Mother.ContactNumber' ,
            MOTHER_PRIMARY_CONTACTNO INT PATH '$.StudentDetails.Mother.PrimaryContact' ,
            #GUARDIAN 
            GUARDIAN_LOGIN VARCHAR(150)  PATH '$.GuardianDetails.LoginId',
            GUARDIAN_LOGIN_PASSWORD VARCHAR(250)  PATH '$.GuardianDetails.Password',
            GUARDIAN_FIRST_NAME VARCHAR(150) PATH '$.GuardianDetails.FirstName',
            GUARDIAN_MIDDLE_NAME VARCHAR(150) PATH '$.GuardianDetails.MiddleName',
            GUARDIAN_LAST_NAME VARCHAR(150) PATH '$.GuardianDetails.LastName',
            GUARDIAN_NOTIFICATION_ID     VARCHAR(150) PATH '$.GuardianDetails.NotificationId',
            GURARDIAN_PRIMARY_CONTACTNO INT PATH '$.GuardianDetails.PrimaryContact',   
            GURARDIAN_DATE_OF_BIRTH DATETIME PATH '$.GuardianDetails.DateOfBirth',              
            GURARDIAN_GENDER VARCHAR(4) PATH '$.GuardianDetails.Sex',              
            GUARDIAN_IMAGE VARCHAR(150) PATH '$.GuardianDetails.ImageName' ,                   
            GUARDIAN_ADDRESS JSON PATH '$.GuardianDetails.Details.Address' ,
            GUARDIAN_CONTACTNO JSON PATH '$.GuardianDetails.Details.ContactNumber' ,
            GUARDIAN_QUALIFICATION VARCHAR(150) PATH '$.GuardianDetails.Details.Qualification' , 
            GUARDIAN_ANNUAL_INCOME VARCHAR(150) PATH '$.GuardianDetails.Details.AnnualIncome' , 
            GUARDIAN_OCCUPATION VARCHAR(150) PATH '$.GuardianDetails.Details.Occupation' 
            
							
						   )
				 ) STUDENT_DETAILS;
START TRANSACTION;
SET V_ACTIVE=1;
SET V_USERTYPEID_FOR_STUDENT=3;
SET V_USERTYPEID_FOR_GUARDIAN=4;
SET V_USER_ID_FOR_STUDENT=0; 
SET V_USER_ID_FOR_GUARDIAN  =0;
SET V_STUDENT_ID=0;
SET V_STUDENT_DETAIL_ID=0;
    #First Student is exits or not if not exists then create user first
	
        SELECT IFNULL(ID,0)  INTO V_USER_ID_FOR_STUDENT
        FROM USER_MASTER WHERE customer_id=J_V_CUSTOMERID AND LOWER(LOGIN_ID)=LOWER(J_V_STUDENT_LOGIN);
	
	IF V_USER_ID_FOR_STUDENT =0 THEN
		CALL SP_INSERT_USER_MASTER(        J_V_STUDENT_LOGIN 	,
                                           J_V_STUDENT_LOGIN_PASSWORD	,
                                           J_V_STUDENT_FIRST_NAME,
                                           J_V_STUDENT_MIDDLE_NAME 	,
                                           J_V_STUDENT_LAST_NAME 	,
			                   V_USERTYPEID_FOR_STUDENT	,
                                           V_ACTIVE	,
                                           J_V_CUSTOMERID	,
                                           J_V_STUDENT_CONTACTNO 	,
                                           J_V_STUDENT_ADDRESS 	,
                                           J_V_STUDENT_NOTIFICATION_ID 	,
                                           J_V_CREATED_DATE	,
                                           J_V_CREATED_BY	,
                                           V_MODIFIED_DATE	,
                                           V_MODIFIED_BY	,
                                           J_V_STUDENT_PRIMARY_CONTACTNO,
                                           V_USER_ID_FOR_STUDENT
									);
	END IF;
	
	SELECT V_USER_ID_FOR_STUDENT;
	#First Guardian is exists or not if not exists then create user first
	
	
	SELECT IFNULL(ID,0)  INTO V_USER_ID_FOR_GUARDIAN
        FROM USER_MASTER WHERE customer_id=J_V_CUSTOMERID AND LOWER(LOGIN_ID)=LOWER(J_V_GUARDIAN_LOGIN);	
		IF V_USER_ID_FOR_GUARDIAN =0 THEN
				CALL SP_INSERT_USER_MASTER(J_V_GUARDIAN_LOGIN 	,
                                          J_V_GUARDIAN_LOGIN_PASSWORD	,
                                          J_V_GUARDIAN_FIRST_NAME,
                                          J_V_GUARDIAN_MIDDLE_NAME 	,
                                          J_V_GUARDIAN_LAST_NAME 	,
					  V_USERTYPEID_FOR_GUARDIAN	,
                                          V_ACTIVE	,
                                          J_V_CUSTOMERID	,
                                          J_V_GUARDIAN_CONTACTNO 	,
                                          J_V_GUARDIAN_ADDRESS 	,
                                          J_V_GUARDIAN_NOTIFICATION_ID 	,
                                          J_V_CREATED_DATE	,
                                          J_V_CREATED_BY	,
                                          V_MODIFIED_DATE	,
                                          V_MODIFIED_BY	,
                                          J_V_GURARDIAN_PRIMARY_CONTACTNO,
                                          V_USER_ID_FOR_GUARDIAN);
		END IF;
		
		SELECT V_USER_ID_FOR_GUARDIAN;
		#Check whether Student exists or not 
		SELECT IFNULL(ID,0)  INTO V_STUDENT_ID
        FROM STUDENT WHERE USER_ID=V_USER_ID_FOR_STUDENT ;	
		
		IF V_STUDENT_ID=0 then 
	
		CALL SP_INSERT_STUDENT
					(
			  
			V_USER_ID_FOR_STUDENT,
			J_V_STUDENT_ROLLNO,
			V_USER_ID_FOR_GUARDIAN,
			J_V_IS_ENROLLED,
			V_ACTIVE,
			J_V_CREATED_BY,
			J_V_CREATED_DATE ,
			V_MODIFIED_BY,
			V_MODIFIED_DATE,
			V_STUDENT_ID
			);
	    END IF;	
         SELECT V_STUDENT_ID ;
		#Check whether Student exists or not 
		SELECT IFNULL(ID,0)  INTO V_STUDENT_DETAIL_ID
        FROM STUDENT_DETAILS WHERE STUDENT_ID=V_STUDENT_ID ;
 
     IF   	V_STUDENT_DETAIL_ID=0 THEN	
		CALL SP_INSERT_STUDENT_DETAILS(
		V_STUDENT_ID,
		J_V_STUDENT_ACADEMIC_INSTITUTE,
		J_V_STUDENT_IMAGE_PATH,
		J_V_FATHER_FIRST_NAME,
		J_V_FATHER_MIDDLE_NAME,
		J_V_FATHER_LAST_NAME,
		J_V_FATHER_PRIMARY_CONTACTNO,
		J_V_FATHER_ANUAL_INCOME,
		J_V_FATHER_QUALIFICATION,
		J_V_FATHER_OCCUPATION,
		J_V_MOTHER_FIRST_NAME,
		J_V_MOTHER_MIDDLE_NAME,
		J_V_MOTHER_LAST_NAME,
		J_V_MOTHER_QUALIFICATION,
		J_V_MOTHER_OCCUPATION,
		J_V_MOTHER_PRIMARY_CONTACTNO,
		J_V_MOTHER_ANUAL_INCOME,
		J_V_STUDENT_DATE_OF_BIRTH ,
		J_V_STUDENT_QUALIFICATION,
		J_V_CREATED_BY,
		J_V_CREATED_DATE,
		V_MODIFIED_BY,
		V_MODIFIED_DATE ,
		V_STUDENT_DETAIL_ID);
          
    END IF;
    
COMMIT;
    
    SET P_OUT_STUDENTID=V_STUDENT_ID;
       
	END */$$
DELIMITER ;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
