CREATE TABLE USER_MASTER_AUDIT (
ID INT (11)PRIMARY KEY AUTO_INCREMENT,
USER_ID INT(11),
LOGIN_ID VARCHAR (150),
PASSWORD VARCHAR (250),
FIRST_NAME VARCHAR (150),
MIDDLE_NAME VARCHAR (150),
LAST_NAME VARCHAR (150),
USER_TYPE_ID INT (11),
CUSTOMER_ID INT (11),
CONTACT_NO JSON ,
ADDRESS JSON ,
NOTIFICATION_ID VARCHAR (150),
IP_ADDRESS VARCHAR (150),
OS_USER VARCHAR(150),
OPERATION INT(2),
OPERATION_DATE DATETIME,
CREATED_DATE DATETIME ,
CREATED_BY INT (11),
MODIFIED_DATE DATETIME ,
MODIFIED_BY INT (11)
);

CREATE TABLE USER_DETAILS (
  ID INT(11) PRIMARY KEY AUTO_INCREMENT,
  USER_ID INT(11)NOT NULL,
  PASSWORD_EXPIRATION_DATE DATETIME,
  LANGUAGE_ID INT(11),
  PAGE_SIZE                   INT(4),
  PWD_VALIDATION_CODE         VARCHAR(100),
  IS_TEMPORARYPASSWORD        INT(2),
  LAST_LOGIN_DATE             DATE,
  LOCK_ATTEMPTS               INT(2),
  CREATED_BY INT(11),
  CREATED_DATE DATETIME,
  MODIFIED_BY INT(11),
  MODIFIED_DATE DATETIME,
  CONSTRAINT USER_DETAILS_FK1 FOREIGN KEY (USER_ID)REFERENCES USER_MASTER(ID),
  CONSTRAINT USER_DETAILS_FK2 FOREIGN KEY (LANGUAGE_ID)REFERENCES LANGUAGE_MASTER(ID)
) ;

CREATE TABLE USER_DETAILS_AUDIT (
  ID INT(11) PRIMARY KEY AUTO_INCREMENT,
  USER_DETAILS_ID INT(11) NOT NULL ,
  USER_ID INT(11)NOT NULL,
  PASSWORD_EXPIRATION_DATE DATETIME,
  LANGUAGE_ID INT(11),
  PAGE_SIZE                   INT(4),
  PWD_VALIDATION_CODE         VARCHAR(100),
  IS_TEMPORARYPASSWORD        INT(2),
  LAST_LOGIN_DATE             DATE,
  LOCK_ATTEMPTS               INT(2),
  CREATED_BY INT(11),
  CREATED_DATE DATETIME,
  MODIFIED_BY INT(11),
  MODIFIED_DATE DATETIME,
  OPERATION  INT(1),
  OPERATION_DATE DATETIME,
  IP_ADDRESS      VARCHAR(100),
  CONSTRAINT USER_DETAILS_AUDIT_FK1 FOREIGN KEY (USER_ID)REFERENCES USER_MASTER(ID),
  CONSTRAINT USER_DETAILS_AUDIT_FK2 FOREIGN KEY (LANGUAGE_ID)REFERENCES LANGUAGE_MASTER(ID),
  CONSTRAINT USER_DETAILS_AUDIT_FK3 FOREIGN KEY (USER_DETAILS_ID)REFERENCES USER_DETAILS(ID)
) ;

CREATE TABLE USER_LOGIN_DETAILS
(
  ID                           INT(11)PRIMARY KEY AUTO_INCREMENT,
  USER_ID                      INT(11),
  LOGIN_DATE                   DATETIME,
  CUSTOMER_ID                  INT(11),
  USER_BROWSER_SYSTEM_DETAILS  JSON,
  LOG_OUT                      DATETIME,
  IS_SUCCESS                   INT(2),
  CREATED_BY                    INT(11),
  CREATED_DATE                  DATE,
  MODIFIED_BY                   INT(11),
  MODIFIED_DATE                 DATETIME
 );



