
CREATE TABLE MODULE_MASTER
(
  ID              INT(4) PRIMARY KEY ,
  CODE            VARCHAR(50),
  NAME            VARCHAR(100),
  DESCRIPTION     VARCHAR(250),
  PARENT_ID       INT(4),
  ACTIVE          INT(1)      DEFAULT 1,
  CREATED_DATE    DATETIME
  );


CREATE  TABLE PRIVILEGE_TYPE
(
  ID             INT(4)PRIMARY KEY,
  NAME           VARCHAR(100)             NOT NULL,
  ACTIVE         INT(1)     NOT NULL DEFAULT 1,
  DESCRIPTION    VARCHAR(250),
  CREATED_DATE   DATE                           
  );


CREATE  TABLE PRIVILEGE_TYPE
(
  ID             INT(4)PRIMARY KEY,
  NAME           VARCHAR(100)             NOT NULL,
  ACTIVE         INT(1)     NOT NULL DEFAULT 1,
  DESCRIPTION    VARCHAR(250),
  CREATED_DATE   DATE                           
  );
  
  
  
CREATE TABLE MODULE_PRIVILEGES
(
  ID             INT(18)PRIMARY KEY,
  MODULE_ID      INT(4),
  PRIVILEGE_TYPE_ID  INT(4),
  ACTIVE         INT(1)                      DEFAULT 1,
  CREATED_DATE   DATE                          
  );



CREATE   TABLE CUSTOMER_BRANCHES
(
ID INTEGER PRIMARY KEY AUTO_INCREMENT,
CUSTOMER_ID INTEGER,
CODE VARCHAR(150)UNIQUE NOT NULL,
NAME VARCHAR(250) UNIQUE NOT NULL,
ACTIVE INTEGER NOT NULL,
CONTACT_NO JSON,
ADDRESS JSON,
OTHER_INFO JSON,
CREATED_DATE DATETIME,
CREATED_BY INTEGER,
CONSTRAINT BRANCH_MASTER_FK FOREIGN KEY(CUSTOMER_ID)REFERENCES CUSTOMER_MASTER(ID)
);
