
CREATE   TABLE CUSTOMER
(
ID INTEGER PRIMARY KEY AUTO_INCREMENT,
CODE VARCHAR(150)UNIQUE NOT NULL,
NAME VARCHAR(250) UNIQUE NOT NULL,
SUB_DOMAIN VARCHAR(100)NOT NULL,
DESCRIPTION VARCHAR(150),
ACTIVE INTEGER NOT NULL,
CONTRACT_NO JSON,
ADDRESS JSON,
OTHER_INFO JSON,
CREATED_DATE DATETIME,
CREATED_BY INTEGER
)ENGINE=INNODB;


CREATE TABLE USER_TYPE
(ID INTEGER PRIMARY KEY ,
 NAME VARCHAR(150),
 CREATED_DATE DATETIME
 )ENGINE=INNODB;

