
CREATE   TABLE CUSTOMER_MASTER
(
ID INTEGER PRIMARY KEY AUTO_INCREMENT,
CODE VARCHAR(150)UNIQUE NOT NULL,
NAME VARCHAR(250) UNIQUE NOT NULL,
SUB_DOMAIN VARCHAR(100)UNIQUE NOT NULL,
DESCRIPTION VARCHAR(150),
ACTIVE INTEGER NOT NULL,
CONTACT_NO JSON,
ADDRESS JSON,
OTHER_INFO JSON,
CREATED_DATE DATETIME,
CREATED_BY INTEGER
)ENGINE=INNODB;


CREATE TABLE USER_TYPE
(ID INTEGER PRIMARY KEY ,
 NAME VARCHAR(150),
 CREATED_DATE DATETIME
 )ENGINE=INNODB;

CREATE TABLE USER_MASTER
(
ID INTEGER PRIMARY KEY AUTO_INCREMENT,
LOGIN_ID VARCHAR(150)NOT NULL ,
PASSWORD VARCHAR(250),
FIRST_NAME VARCHAR(150),
MIDDLE_NAME VARCHAR(150),
LAST_NAME VARCHAR(150),
USER_TYPE_ID INTEGER,
CUSTOMER_ID INTEGER,
CONTACT_NO JSON,
ADDRESS JSON,
NOTIFICATION_ID VARCHAR(150),
CREATED_DATE DATETIME,
CREATED_BY INTEGER,
MODIFIED_DATE DATETIME,
MODIFIED_BY INTEGER,
CONSTRAINT USER_MASTER_FK1
FOREIGN KEY  (USER_TYPE_ID)
REFERENCES USER_TYPE(ID),
CONSTRAINT USER_MASTER_FK2
FOREIGN KEY  (CUSTOMER_ID)
REFERENCES CUSTOMER_MASTER(ID)
);
