/*
SQLyog Community v13.1.5  (64 bit)
MySQL - 8.0.17 : Database - ved_soft_db
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`ved_soft_db` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;

USE `ved_soft_db`;

/*Table structure for table `ACADEMIC_YEARS` */

DROP TABLE IF EXISTS `ACADEMIC_YEARS`;

CREATE TABLE `ACADEMIC_YEARS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ACADEMIC_YEAR` varchar(50) DEFAULT NULL,
  `ACTIVE` int(1) DEFAULT NULL,
  `CREATED_BY` int(11) DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT NULL,
  `MODIFIED_BY` int(11) DEFAULT NULL,
  `MODIFIED_DATE` datetime DEFAULT NULL,
  `CUSTOMER_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `ADMISSION_TYPE` */

DROP TABLE IF EXISTS `ADMISSION_TYPE`;

CREATE TABLE `ADMISSION_TYPE` (
  `ID` int(11) NOT NULL,
  `NAME` varchar(100) DEFAULT NULL,
  `ACTIVE` int(1) DEFAULT NULL,
  `CREATED_BY` int(11) DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT NULL,
  `MODIFIED_BY` int(11) DEFAULT NULL,
  `MODIFIED_DATE` datetime DEFAULT NULL,
  `CUSTOMER_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `BANK` */

DROP TABLE IF EXISTS `BANK`;

CREATE TABLE `BANK` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(150) DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT NULL,
  `CUSTOMER_ID` int(11) DEFAULT NULL,
  `ACTIVE` int(1) DEFAULT NULL,
  `CREATED_BY` int(11) DEFAULT NULL,
  `MODIFIED_BY` int(11) DEFAULT NULL,
  `MODIFIED_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `BRANCH_COURSES` */

DROP TABLE IF EXISTS `BRANCH_COURSES`;

CREATE TABLE `BRANCH_COURSES` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CUSTOMER_COURSES_ID` varchar(250) DEFAULT NULL,
  `BRANCH_ID` int(11) DEFAULT NULL,
  `ACADEMIC_YEAR_ID` int(11) DEFAULT NULL,
  `ACTIVE` int(11) DEFAULT NULL,
  `COURSE_DURATION_MONTHS` varchar(250) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `BRANCH_COURSES_FK2` (`BRANCH_ID`),
  CONSTRAINT `BRANCH_COURSES_FK2` FOREIGN KEY (`BRANCH_ID`) REFERENCES `CUSTOMER_BRANCHES` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `CUSTOMER_BRANCHES` */

DROP TABLE IF EXISTS `CUSTOMER_BRANCHES`;

CREATE TABLE `CUSTOMER_BRANCHES` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CUSTOMER_ID` int(11) DEFAULT NULL,
  `CODE` varchar(150) NOT NULL,
  `NAME` varchar(250) NOT NULL,
  `ACTIVE` int(11) NOT NULL,
  `CONTACT_NO` json DEFAULT NULL,
  `ADDRESS` json DEFAULT NULL,
  `OTHER_INFO` json DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT NULL,
  `CREATED_BY` int(11) DEFAULT NULL,
  `MODIFIED_DATE` datetime DEFAULT NULL,
  `MODIFIED_BY` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `CODE` (`CODE`),
  UNIQUE KEY `NAME` (`NAME`),
  KEY `BRANCH_MASTER_FK` (`CUSTOMER_ID`),
  CONSTRAINT `BRANCH_MASTER_FK` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `CUSTOMER_MASTER` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `CUSTOMER_COURSES` */

DROP TABLE IF EXISTS `CUSTOMER_COURSES`;

CREATE TABLE `CUSTOMER_COURSES` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(250) DEFAULT NULL,
  `CUSTOMER_ID` int(11) DEFAULT NULL,
  `ACTIVE` int(1) unsigned DEFAULT '1',
  `VEDIC_COURSE_ID` int(11) DEFAULT NULL,
  `COURSE_TYPE_ID` int(11) DEFAULT NULL,
  `COURSE_DESCRIPTION` varchar(250) DEFAULT NULL,
  `DURATION` int(11) DEFAULT NULL,
  `DURATION_UOM` varchar(50) DEFAULT NULL,
  `COURSE_COST` decimal(10,0) DEFAULT NULL,
  `CREATED_BY` int(11) DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT NULL,
  `MODIFIED_BY` int(11) DEFAULT NULL,
  `MODIFIED_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `CUSTOMER_COURSES_FK1` (`VEDIC_COURSE_ID`),
  KEY `CUSTOMER_COURSES_FK2` (`CUSTOMER_ID`),
  CONSTRAINT `CUSTOMER_COURSES_FK1` FOREIGN KEY (`VEDIC_COURSE_ID`) REFERENCES `VEDIC_COURSES_MASTER` (`ID`),
  CONSTRAINT `CUSTOMER_COURSES_FK2` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `CUSTOMER_MASTER` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `CUSTOMER_COURSE_SUBJECT_MAPPING` */

DROP TABLE IF EXISTS `CUSTOMER_COURSE_SUBJECT_MAPPING`;

CREATE TABLE `CUSTOMER_COURSE_SUBJECT_MAPPING` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CUSTOMER_ID` int(11) NOT NULL,
  `CUSTOMER_COURSE_ID` int(11) NOT NULL,
  `CUSTOMER_SUBJECT_HIERACHY_ID` int(11) NOT NULL,
  `ACTIVE` int(1) DEFAULT '1',
  `CREATED_BY` int(11) DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT NULL,
  `MODIFIED_BY` int(11) DEFAULT NULL,
  `MODIFIED_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `CUSTOMER_COURSE_HIERACHY_MAPPING_FK1` (`CUSTOMER_SUBJECT_HIERACHY_ID`),
  KEY `CUSTOMER_COURSE_HIERACHY_MAPPING_FK2` (`CUSTOMER_COURSE_ID`),
  KEY `CUSTOMER_COURSE_HIERACHY_MAPPING_FK3` (`CUSTOMER_ID`),
  CONSTRAINT `CUSTOMER_COURSE_HIERACHY_MAPPING_FK1` FOREIGN KEY (`CUSTOMER_SUBJECT_HIERACHY_ID`) REFERENCES `CUSTOMER_SUBJECT_HIRARCHY` (`ID`),
  CONSTRAINT `CUSTOMER_COURSE_HIERACHY_MAPPING_FK2` FOREIGN KEY (`CUSTOMER_COURSE_ID`) REFERENCES `CUSTOMER_COURSES` (`ID`),
  CONSTRAINT `CUSTOMER_COURSE_HIERACHY_MAPPING_FK3` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `CUSTOMER_MASTER` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `CUSTOMER_EDUCATIONAL_INSTITUTIONS` */

DROP TABLE IF EXISTS `CUSTOMER_EDUCATIONAL_INSTITUTIONS`;

CREATE TABLE `CUSTOMER_EDUCATIONAL_INSTITUTIONS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `INSTITUTION_TYPE_ID` int(11) DEFAULT NULL,
  `CUSTOMER_ID` int(11) DEFAULT NULL,
  `NAME` varchar(250) DEFAULT NULL,
  `ACTIVE` int(11) DEFAULT NULL,
  `CREATED_BY` int(11) DEFAULT NULL,
  `CREATED_DATE` date DEFAULT NULL,
  `MODIFIED_BY` int(11) DEFAULT NULL,
  `MODIFIED_DATE` date DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `CUSTOMER_EDUC_INSTITUTION_FK1` (`INSTITUTION_TYPE_ID`),
  KEY `CUSTOMER_EDUC_INSTITUTION_FK2` (`CUSTOMER_ID`),
  CONSTRAINT `CUSTOMER_EDUC_INSTITUTION_FK1` FOREIGN KEY (`INSTITUTION_TYPE_ID`) REFERENCES `VEDIC_INSTITUTION_TYPE` (`ID`),
  CONSTRAINT `CUSTOMER_EDUC_INSTITUTION_FK2` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `CUSTOMER_MASTER` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `CUSTOMER_MASTER` */

DROP TABLE IF EXISTS `CUSTOMER_MASTER`;

CREATE TABLE `CUSTOMER_MASTER` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CODE` varchar(150) NOT NULL,
  `NAME` varchar(250) NOT NULL,
  `SUB_DOMAIN` varchar(100) NOT NULL,
  `DESCRIPTION` varchar(150) DEFAULT NULL,
  `ACTIVE` int(11) NOT NULL,
  `CONTACT_NO` json DEFAULT NULL,
  `ADDRESS` json DEFAULT NULL,
  `OTHER_INFO` json DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT NULL,
  `CREATED_BY` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `CODE` (`CODE`),
  UNIQUE KEY `NAME` (`NAME`),
  UNIQUE KEY `SUB_DOMAIN` (`SUB_DOMAIN`)
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `CUSTOMER_ROLES` */

DROP TABLE IF EXISTS `CUSTOMER_ROLES`;

CREATE TABLE `CUSTOMER_ROLES` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(250) DEFAULT NULL,
  `DESCRIPTION` varchar(250) DEFAULT NULL,
  `CUSTOMER_ID` int(11) NOT NULL,
  `ACTIVE` int(1) DEFAULT NULL,
  `CREATED_BY` int(11) DEFAULT NULL,
  `CREATED_DATE` date DEFAULT NULL,
  `MODIFIED_BY` int(11) DEFAULT NULL,
  `MODIFIED_DATE` date DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `CUSTOMER_ROLES_FK1` (`CUSTOMER_ID`),
  CONSTRAINT `CUSTOMER_ROLES_FK1` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `CUSTOMER_MASTER` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `CUSTOMER_ROLE_MODULE_PRIVILEGES` */

DROP TABLE IF EXISTS `CUSTOMER_ROLE_MODULE_PRIVILEGES`;

CREATE TABLE `CUSTOMER_ROLE_MODULE_PRIVILEGES` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CUSTOMER_ROLE_ID` int(11) DEFAULT NULL,
  `MODULE_PRIVILEGE_ID` int(11) DEFAULT NULL,
  `ACTIVE` int(1) DEFAULT NULL,
  `CREATED_BY` int(11) DEFAULT NULL,
  `CREATED_DATE` date DEFAULT NULL,
  `MODIFIED_BY` int(11) DEFAULT NULL,
  `MODIFIED_DATE` date DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `CUSTOMER_ROLE_MODULE_PRIVILEGES_FK1` (`CUSTOMER_ROLE_ID`),
  KEY `CUSTOMER_ROLE_MODULE_PRIVILEGES_FK2` (`MODULE_PRIVILEGE_ID`),
  CONSTRAINT `CUSTOMER_ROLE_MODULE_PRIVILEGES_ibfk_1` FOREIGN KEY (`CUSTOMER_ROLE_ID`) REFERENCES `CUSTOMER_ROLES` (`ID`),
  CONSTRAINT `CUSTOMER_ROLE_MODULE_PRIVILEGES_ibfk_2` FOREIGN KEY (`MODULE_PRIVILEGE_ID`) REFERENCES `MODULE_PRIVILEGES` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `CUSTOMER_ROLE_PRIVILEGES` */

DROP TABLE IF EXISTS `CUSTOMER_ROLE_PRIVILEGES`;

CREATE TABLE `CUSTOMER_ROLE_PRIVILEGES` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CUSTOMER_ID` int(11) DEFAULT NULL,
  `CUSTOMER_ROLE_ID` int(11) DEFAULT NULL,
  `PRIVILEGE_TYPE_ID` int(11) DEFAULT NULL,
  `ACTIVE` int(1) DEFAULT NULL,
  `CREATED_BY` int(11) DEFAULT NULL,
  `CREATED_DATE` date DEFAULT NULL,
  `MODIFIED_BY` int(11) DEFAULT NULL,
  `MODIFIED_DATE` date DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `CUSTOMER_ROLES_FK1` (`CUSTOMER_ROLE_ID`),
  CONSTRAINT `CUSTOMER_ROLE_PRIVILEGES_ibfk_1` FOREIGN KEY (`CUSTOMER_ROLE_ID`) REFERENCES `CUSTOMER_ROLES` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `CUSTOMER_SUBJECT_HIRARCHY` */

DROP TABLE IF EXISTS `CUSTOMER_SUBJECT_HIRARCHY`;

CREATE TABLE `CUSTOMER_SUBJECT_HIRARCHY` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(250) DEFAULT NULL,
  `CUSTOMER_ID` int(11) DEFAULT NULL,
  `PARENT_ID` int(11) DEFAULT NULL,
  `HIERACHY_LEVEL` int(11) DEFAULT NULL,
  `ACTIVE` int(1) DEFAULT '1',
  `CREATED_BY` int(11) DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT NULL,
  `MODIFIED_BY` int(11) DEFAULT NULL,
  `MODIFIED_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `COURSES_STRUCTURE_HIERACHY_FK` (`PARENT_ID`),
  KEY `CUSTOMER_COURSE_HIERACHY_FK2` (`CUSTOMER_ID`),
  CONSTRAINT `COURSES_STRUCTURE_HIERACHY_FK` FOREIGN KEY (`PARENT_ID`) REFERENCES `CUSTOMER_SUBJECT_HIRARCHY` (`ID`),
  CONSTRAINT `CUSTOMER_COURSE_HIERACHY_FK2` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `CUSTOMER_MASTER` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=29 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `DEPARTMENT` */

DROP TABLE IF EXISTS `DEPARTMENT`;

CREATE TABLE `DEPARTMENT` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `BRANCH_ID` int(11) DEFAULT NULL,
  `NAME` varchar(250) DEFAULT NULL,
  `DESCRIPTION` varchar(250) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `DEPARTMENT_FK` (`BRANCH_ID`),
  CONSTRAINT `DEPARTMENT_FK` FOREIGN KEY (`BRANCH_ID`) REFERENCES `CUSTOMER_BRANCHES` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `JAI_MAA_BHAWANI` */

DROP TABLE IF EXISTS `JAI_MAA_BHAWANI`;

CREATE TABLE `JAI_MAA_BHAWANI` (
  `DESCRIPTION` varchar(2000) DEFAULT NULL,
  `CREATEDDATE` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `LANGUAGE_MASTER` */

DROP TABLE IF EXISTS `LANGUAGE_MASTER`;

CREATE TABLE `LANGUAGE_MASTER` (
  `ID` int(4) NOT NULL,
  `NAME` varchar(50) DEFAULT NULL,
  `CULTURE_CODE` varchar(5) DEFAULT NULL,
  `ACTIVE` tinyint(1) DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `MODULE_MASTER` */

DROP TABLE IF EXISTS `MODULE_MASTER`;

CREATE TABLE `MODULE_MASTER` (
  `ID` int(4) NOT NULL,
  `CODE` varchar(50) DEFAULT NULL,
  `NAME` varchar(100) DEFAULT NULL,
  `DESCRIPTION` varchar(250) DEFAULT NULL,
  `PARENT_ID` int(4) DEFAULT NULL,
  `ACTIVE` int(1) DEFAULT '1',
  `CREATED_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `MODULE_PRIVILEGES` */

DROP TABLE IF EXISTS `MODULE_PRIVILEGES`;

CREATE TABLE `MODULE_PRIVILEGES` (
  `ID` int(18) NOT NULL,
  `MODULE_ID` int(4) DEFAULT NULL,
  `PRIVILEGE_TYPE_ID` int(4) DEFAULT NULL,
  `ACTIVE` int(1) DEFAULT '1',
  `CREATED_DATE` date DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `PRIVILEGE_TYPE` */

DROP TABLE IF EXISTS `PRIVILEGE_TYPE`;

CREATE TABLE `PRIVILEGE_TYPE` (
  `ID` int(4) NOT NULL,
  `NAME` varchar(100) NOT NULL,
  `ACTIVE` int(1) NOT NULL DEFAULT '1',
  `DESCRIPTION` varchar(250) DEFAULT NULL,
  `CREATED_DATE` date DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `STUDENT` */

DROP TABLE IF EXISTS `STUDENT`;

CREATE TABLE `STUDENT` (
  `ID` int(11) NOT NULL,
  `USER_ID` int(11) DEFAULT NULL,
  `FATHER_USER_ID` int(11) DEFAULT NULL,
  `MOTHER_USER_ID` int(11) DEFAULT NULL,
  `GUARDIAN_USER_ID` int(11) DEFAULT NULL,
  `IS_ENROLLED` int(11) DEFAULT NULL,
  `ACTIVE` int(11) DEFAULT NULL,
  `CREATED_BY` int(11) DEFAULT NULL,
  `CREATED_DATE` date DEFAULT NULL,
  `MODIFIED_BY` int(11) DEFAULT NULL,
  `MODIFIED_DATE` date DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `STUDENT_FK1` (`USER_ID`),
  KEY `STUDENT_FK3` (`FATHER_USER_ID`),
  KEY `STUDENT_FK4` (`MOTHER_USER_ID`),
  CONSTRAINT `STUDENT_FK1` FOREIGN KEY (`USER_ID`) REFERENCES `USER_MASTER` (`ID`),
  CONSTRAINT `STUDENT_FK3` FOREIGN KEY (`FATHER_USER_ID`) REFERENCES `USER_MASTER` (`ID`),
  CONSTRAINT `STUDENT_FK4` FOREIGN KEY (`MOTHER_USER_ID`) REFERENCES `USER_MASTER` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `STUDENT_ADMISSION_DETAILS` */

DROP TABLE IF EXISTS `STUDENT_ADMISSION_DETAILS`;

CREATE TABLE `STUDENT_ADMISSION_DETAILS` (
  `ID` int(11) NOT NULL,
  `STUDENT_ID` int(11) DEFAULT NULL,
  `BRANCH_ID` int(11) DEFAULT NULL,
  `ACADEMIC_YEARID` int(11) DEFAULT NULL,
  `DATE_OF_ADMISSION` date DEFAULT NULL,
  `ADMISSION_TYPEID` int(11) DEFAULT NULL,
  `CREATED_DATE` date DEFAULT NULL,
  `CREATED_BY` int(11) DEFAULT NULL,
  `MODIFIED_DATE` date DEFAULT NULL,
  `MODIFIED_BY` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `STUDENT_ADMISSION_DETAILS_FK1` (`STUDENT_ID`),
  KEY `STUDENT_ADMISSION_DETAILS_FK2` (`BRANCH_ID`),
  KEY `STUDENT_ADMISSION_DETAILS_FK3` (`ADMISSION_TYPEID`),
  KEY `STUDENT_ADMISSION_DETAILS_FK4` (`ACADEMIC_YEARID`),
  CONSTRAINT `STUDENT_ADMISSION_DETAILS_FK1` FOREIGN KEY (`STUDENT_ID`) REFERENCES `STUDENT` (`ID`),
  CONSTRAINT `STUDENT_ADMISSION_DETAILS_FK2` FOREIGN KEY (`BRANCH_ID`) REFERENCES `CUSTOMER_BRANCHES` (`ID`),
  CONSTRAINT `STUDENT_ADMISSION_DETAILS_FK3` FOREIGN KEY (`ADMISSION_TYPEID`) REFERENCES `ADMISSION_TYPE` (`ID`),
  CONSTRAINT `STUDENT_ADMISSION_DETAILS_FK4` FOREIGN KEY (`ACADEMIC_YEARID`) REFERENCES `ACADEMIC_YEARS` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `STUDENT_COURSES` */

DROP TABLE IF EXISTS `STUDENT_COURSES`;

CREATE TABLE `STUDENT_COURSES` (
  `ID` int(11) NOT NULL,
  `STUDENT_ID` int(11) DEFAULT NULL,
  `BRANCH_COURSES_ID` int(11) DEFAULT NULL,
  `COURSE_FEE_AMOUNT` decimal(10,0) DEFAULT NULL,
  `DISCOUNT_ALLOWED` int(11) DEFAULT NULL,
  `DISCOUNTED_FEE_AMOUNT` decimal(10,0) DEFAULT NULL,
  `ACTIVE` int(11) DEFAULT NULL,
  `CREATED_DATE` date DEFAULT NULL,
  `CREATED_BY` int(11) DEFAULT NULL,
  `MODIFIED_DATE` date DEFAULT NULL,
  `MODIFIED_BY` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `STUDENT_COURSES_FK1` (`STUDENT_ID`),
  KEY `STUDENT_COURSES_FK2` (`BRANCH_COURSES_ID`),
  CONSTRAINT `STUDENT_COURSES_FK1` FOREIGN KEY (`STUDENT_ID`) REFERENCES `STUDENT` (`ID`),
  CONSTRAINT `STUDENT_COURSES_FK2` FOREIGN KEY (`BRANCH_COURSES_ID`) REFERENCES `BRANCH_COURSES` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `USER_DETAILS` */

DROP TABLE IF EXISTS `USER_DETAILS`;

CREATE TABLE `USER_DETAILS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `USER_ID` int(11) NOT NULL,
  `PASSWORD_EXPIRATION_DATE` datetime DEFAULT NULL,
  `LANGUAGE_ID` int(11) DEFAULT NULL,
  `PAGE_SIZE` int(4) DEFAULT NULL,
  `PWD_VALIDATION_CODE` varchar(100) DEFAULT NULL,
  `IS_TEMPORARYPASSWORD` int(2) DEFAULT NULL,
  `LAST_LOGIN_DATE` date DEFAULT NULL,
  `LOCK_ATTEMPTS` int(2) DEFAULT NULL,
  `CREATED_BY` int(11) DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT NULL,
  `MODIFIED_BY` int(11) DEFAULT NULL,
  `MODIFIED_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `USER_DETAILS_FK1` (`USER_ID`),
  KEY `USER_DETAILS_FK2` (`LANGUAGE_ID`),
  CONSTRAINT `USER_DETAILS_FK1` FOREIGN KEY (`USER_ID`) REFERENCES `USER_MASTER` (`ID`),
  CONSTRAINT `USER_DETAILS_FK2` FOREIGN KEY (`LANGUAGE_ID`) REFERENCES `LANGUAGE_MASTER` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `USER_DETAILS_AUDIT` */

DROP TABLE IF EXISTS `USER_DETAILS_AUDIT`;

CREATE TABLE `USER_DETAILS_AUDIT` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `USER_DETAILS_ID` int(11) NOT NULL,
  `USER_ID` int(11) NOT NULL,
  `PASSWORD_EXPIRATION_DATE` datetime DEFAULT NULL,
  `LANGUAGE_ID` int(11) DEFAULT NULL,
  `PAGE_SIZE` int(4) DEFAULT NULL,
  `PWD_VALIDATION_CODE` varchar(100) DEFAULT NULL,
  `IS_TEMPORARYPASSWORD` int(2) DEFAULT NULL,
  `LAST_LOGIN_DATE` date DEFAULT NULL,
  `LOCK_ATTEMPTS` int(2) DEFAULT NULL,
  `CREATED_BY` int(11) DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT NULL,
  `MODIFIED_BY` int(11) DEFAULT NULL,
  `MODIFIED_DATE` datetime DEFAULT NULL,
  `OPERATION` int(1) DEFAULT NULL,
  `OPERATION_DATE` datetime DEFAULT NULL,
  `IP_ADDRESS` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `USER_DETAILS_AUDIT_FK1` (`USER_ID`),
  KEY `USER_DETAILS_AUDIT_FK2` (`LANGUAGE_ID`),
  KEY `USER_DETAILS_AUDIT_FK3` (`USER_DETAILS_ID`),
  CONSTRAINT `USER_DETAILS_AUDIT_FK1` FOREIGN KEY (`USER_ID`) REFERENCES `USER_MASTER` (`ID`),
  CONSTRAINT `USER_DETAILS_AUDIT_FK2` FOREIGN KEY (`LANGUAGE_ID`) REFERENCES `LANGUAGE_MASTER` (`ID`),
  CONSTRAINT `USER_DETAILS_AUDIT_FK3` FOREIGN KEY (`USER_DETAILS_ID`) REFERENCES `USER_DETAILS` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `USER_LOGIN_DETAILS` */

DROP TABLE IF EXISTS `USER_LOGIN_DETAILS`;

CREATE TABLE `USER_LOGIN_DETAILS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `USER_ID` int(11) DEFAULT NULL,
  `LOGIN_DATE` datetime DEFAULT NULL,
  `CUSTOMER_ID` int(11) DEFAULT NULL,
  `USER_BROWSER_SYSTEM_DETAILS` json DEFAULT NULL,
  `LOG_OUT` datetime DEFAULT NULL,
  `IS_SUCCESS` int(2) DEFAULT NULL,
  `CREATED_BY` int(11) DEFAULT NULL,
  `CREATED_DATE` date DEFAULT NULL,
  `MODIFIED_BY` int(11) DEFAULT NULL,
  `MODIFIED_DATE` datetime DEFAULT NULL,
  `LOGIN_REFRESH_TOKEN` varchar(2000) DEFAULT NULL,
  `LOGIN_TOKEN` varchar(2000) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=77 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `USER_MASTER` */

DROP TABLE IF EXISTS `USER_MASTER`;

CREATE TABLE `USER_MASTER` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `LOGIN_ID` varchar(150) NOT NULL,
  `PASSWORD` varchar(250) DEFAULT NULL,
  `FIRST_NAME` varchar(150) DEFAULT NULL,
  `MIDDLE_NAME` varchar(150) DEFAULT NULL,
  `LAST_NAME` varchar(150) DEFAULT NULL,
  `USER_TYPE_ID` int(11) DEFAULT NULL,
  `ACTIVE` int(1) DEFAULT NULL,
  `CUSTOMER_ID` int(11) DEFAULT NULL,
  `CONTACT_NO` json DEFAULT NULL,
  `ADDRESS` json DEFAULT NULL,
  `NOTIFICATION_ID` varchar(150) DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT NULL,
  `CREATED_BY` int(11) DEFAULT NULL,
  `MODIFIED_DATE` datetime DEFAULT NULL,
  `MODIFIED_BY` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `USER_MASTER_FK1` (`USER_TYPE_ID`),
  KEY `USER_MASTER_FK2` (`CUSTOMER_ID`),
  CONSTRAINT `USER_MASTER_FK1` FOREIGN KEY (`USER_TYPE_ID`) REFERENCES `USER_TYPE` (`ID`),
  CONSTRAINT `USER_MASTER_FK2` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `CUSTOMER_MASTER` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `USER_MASTER_AUDIT` */

DROP TABLE IF EXISTS `USER_MASTER_AUDIT`;

CREATE TABLE `USER_MASTER_AUDIT` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `USER_ID` int(11) DEFAULT NULL,
  `LOGIN_ID` varchar(150) DEFAULT NULL,
  `PASSWORD` varchar(250) DEFAULT NULL,
  `FIRST_NAME` varchar(150) DEFAULT NULL,
  `MIDDLE_NAME` varchar(150) DEFAULT NULL,
  `LAST_NAME` varchar(150) DEFAULT NULL,
  `USER_TYPE_ID` int(11) DEFAULT NULL,
  `CUSTOMER_ID` int(11) DEFAULT NULL,
  `CONTACT_NO` json DEFAULT NULL,
  `ADDRESS` json DEFAULT NULL,
  `NOTIFICATION_ID` varchar(150) DEFAULT NULL,
  `IP_ADDRESS` varchar(150) DEFAULT NULL,
  `OS_USER` varchar(150) DEFAULT NULL,
  `OPERATION` int(2) DEFAULT NULL,
  `OPERATION_DATE` datetime DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT NULL,
  `CREATED_BY` int(11) DEFAULT NULL,
  `MODIFIED_DATE` datetime DEFAULT NULL,
  `MODIFIED_BY` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `USER_TYPE` */

DROP TABLE IF EXISTS `USER_TYPE`;

CREATE TABLE `USER_TYPE` (
  `ID` int(11) NOT NULL,
  `name` varchar(150) DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `VEDIC_COURSES_MASTER` */

DROP TABLE IF EXISTS `VEDIC_COURSES_MASTER`;

CREATE TABLE `VEDIC_COURSES_MASTER` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(250) DEFAULT NULL,
  `COURSE_TYPE_ID` int(11) DEFAULT NULL,
  `COURSE_DESCRIPTION` varchar(250) DEFAULT NULL,
  `COURSE_DURATION_MONTHS` varchar(250) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `COURSES_FK` (`COURSE_TYPE_ID`),
  CONSTRAINT `COURSES_FK` FOREIGN KEY (`COURSE_TYPE_ID`) REFERENCES `VEDIC_COURSE_TYPE` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `VEDIC_COURSE_HIERACHY` */

DROP TABLE IF EXISTS `VEDIC_COURSE_HIERACHY`;

CREATE TABLE `VEDIC_COURSE_HIERACHY` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(250) DEFAULT NULL,
  `PARENT_ID` int(11) DEFAULT NULL,
  `ACTIVE` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `COURSES_STRUCTURE_HIERACHY_FK1` (`PARENT_ID`),
  CONSTRAINT `COURSES_STRUCTURE_HIERACHY_FK1` FOREIGN KEY (`PARENT_ID`) REFERENCES `VEDIC_COURSE_HIERACHY` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `VEDIC_COURSE_HIERACHY_LEVEL` */

DROP TABLE IF EXISTS `VEDIC_COURSE_HIERACHY_LEVEL`;

CREATE TABLE `VEDIC_COURSE_HIERACHY_LEVEL` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(250) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `VEDIC_COURSE_HIERACHY_MAPPING` */

DROP TABLE IF EXISTS `VEDIC_COURSE_HIERACHY_MAPPING`;

CREATE TABLE `VEDIC_COURSE_HIERACHY_MAPPING` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `COURSE_ID` int(11) NOT NULL,
  `COURSE_HIERACHY_ID` int(11) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `VEDIC_COURSE_HIERACHY_MAPPING_FK1` (`COURSE_HIERACHY_ID`),
  KEY `VEDIC_COURSE_HIERACHY_MAPPING_FK2` (`COURSE_ID`),
  CONSTRAINT `VEDIC_COURSE_HIERACHY_MAPPING_FK1` FOREIGN KEY (`COURSE_HIERACHY_ID`) REFERENCES `VEDIC_COURSE_HIERACHY` (`ID`),
  CONSTRAINT `VEDIC_COURSE_HIERACHY_MAPPING_FK2` FOREIGN KEY (`COURSE_ID`) REFERENCES `VEDIC_COURSES_MASTER` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `VEDIC_COURSE_TYPE` */

DROP TABLE IF EXISTS `VEDIC_COURSE_TYPE`;

CREATE TABLE `VEDIC_COURSE_TYPE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `COURSE_TYPE_NAME` varchar(250) DEFAULT NULL,
  `EDUCATIONAL_INSTITUTIONS_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `COURSE_TYPE_FK` (`EDUCATIONAL_INSTITUTIONS_ID`),
  CONSTRAINT `COURSE_TYPE_FK` FOREIGN KEY (`EDUCATIONAL_INSTITUTIONS_ID`) REFERENCES `VEDIC_EDUCATIONAL_INSTITUTIONS` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `VEDIC_EDUCATIONAL_INSTITUTIONS` */

DROP TABLE IF EXISTS `VEDIC_EDUCATIONAL_INSTITUTIONS`;

CREATE TABLE `VEDIC_EDUCATIONAL_INSTITUTIONS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `INSTITUTION_TYPE_ID` int(11) DEFAULT NULL,
  `NAME` varchar(250) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `EDUCATIONAL_INSTITUTIONS_FK` (`INSTITUTION_TYPE_ID`),
  CONSTRAINT `EDUCATIONAL_INSTITUTIONS_FK` FOREIGN KEY (`INSTITUTION_TYPE_ID`) REFERENCES `VEDIC_INSTITUTION_TYPE` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `VEDIC_INSTITUTION_TYPE` */

DROP TABLE IF EXISTS `VEDIC_INSTITUTION_TYPE`;

CREATE TABLE `VEDIC_INSTITUTION_TYPE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(250) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `VEDIC_ROLES_PRIVILEGES` */

DROP TABLE IF EXISTS `VEDIC_ROLES_PRIVILEGES`;

CREATE TABLE `VEDIC_ROLES_PRIVILEGES` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ROLE_ID` int(11) DEFAULT NULL,
  `PRIVILEG_TYPE_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/* Procedure structure for procedure `SP_Get_All_Customers` */

/*!50003 DROP PROCEDURE IF EXISTS  `SP_Get_All_Customers` */;

DELIMITER $$

/*!50003 CREATE DEFINER=`trishakti`@`%` PROCEDURE `SP_Get_All_Customers`()
BEGIN
    SELECT * FROM CUSTOMER_MASTER;
	

	END */$$
DELIMITER ;

/* Procedure structure for procedure `SP_INSERT_CUSTOMER` */

/*!50003 DROP PROCEDURE IF EXISTS  `SP_INSERT_CUSTOMER` */;

DELIMITER $$

/*!50003 CREATE DEFINER=`trishakti`@`%` PROCEDURE `SP_INSERT_CUSTOMER`(
        IN  p_NAME                    VARCHAR(150), 
        IN  p_CODE                    VARCHAR(150)   
         )
BEGIN

    INSERT INTO CUSTOMER_MASTER(CODE ,NAME )VALUES(p_CODE , p_NAME) ; 
	END */$$
DELIMITER ;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
